// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"openxdr/server/ent/incident"
	"openxdr/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AlertUpdate is the builder for updating Alert entities.
type AlertUpdate struct {
	config
	hooks    []Hook
	mutation *AlertMutation
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdate) Where(ps ...predicate.Alert) *AlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTs sets the "ts" field.
func (_u *AlertUpdate) SetTs(v time.Time) *AlertUpdate {
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableTs(v *time.Time) *AlertUpdate {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *AlertUpdate) SetRuleID(v string) *AlertUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableRuleID(v *string) *AlertUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *AlertUpdate) SetSeverity(v int16) *AlertUpdate {
	_u.mutation.ResetSeverity()
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableSeverity(v *int16) *AlertUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// AddSeverity adds value to the "severity" field.
func (_u *AlertUpdate) AddSeverity(v int16) *AlertUpdate {
	_u.mutation.AddSeverity(v)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *AlertUpdate) SetEventID(v uuid.UUID) *AlertUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableEventID(v *uuid.UUID) *AlertUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// ClearEventID clears the value of the "event_id" field.
func (_u *AlertUpdate) ClearEventID() *AlertUpdate {
	_u.mutation.ClearEventID()
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *AlertUpdate) SetAssetID(v uuid.UUID) *AlertUpdate {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableAssetID(v *uuid.UUID) *AlertUpdate {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// ClearAssetID clears the value of the "asset_id" field.
func (_u *AlertUpdate) ClearAssetID() *AlertUpdate {
	_u.mutation.ClearAssetID()
	return _u
}

// SetIncidentID sets the "incident_id" field.
func (_u *AlertUpdate) SetIncidentID(v uuid.UUID) *AlertUpdate {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableIncidentID(v *uuid.UUID) *AlertUpdate {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// ClearIncidentID clears the value of the "incident_id" field.
func (_u *AlertUpdate) ClearIncidentID() *AlertUpdate {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetCount sets the "count" field.
func (_u *AlertUpdate) SetCount(v int) *AlertUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableCount(v *int) *AlertUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *AlertUpdate) AddCount(v int) *AlertUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetLastTs sets the "last_ts" field.
func (_u *AlertUpdate) SetLastTs(v time.Time) *AlertUpdate {
	_u.mutation.SetLastTs(v)
	return _u
}

// SetNillableLastTs sets the "last_ts" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableLastTs(v *time.Time) *AlertUpdate {
	if v != nil {
		_u.SetLastTs(*v)
	}
	return _u
}

// ClearLastTs clears the value of the "last_ts" field.
func (_u *AlertUpdate) ClearLastTs() *AlertUpdate {
	_u.mutation.ClearLastTs()
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *AlertUpdate) SetEvent(v *Event) *AlertUpdate {
	return _u.SetEventID(v.ID)
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *AlertUpdate) SetAsset(v *Asset) *AlertUpdate {
	return _u.SetAssetID(v.ID)
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_u *AlertUpdate) SetIncident(v *Incident) *AlertUpdate {
	return _u.SetIncidentID(v.ID)
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdate) Mutation() *AlertMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *AlertUpdate) ClearEvent() *AlertUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *AlertUpdate) ClearAsset() *AlertUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// ClearIncident clears the "incident" edge to the Incident entity.
func (_u *AlertUpdate) ClearIncident() *AlertUpdate {
	_u.mutation.ClearIncident()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(alert.FieldTs, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(alert.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(alert.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedSeverity(); ok {
		_spec.AddField(alert.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(alert.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(alert.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastTs(); ok {
		_spec.SetField(alert.FieldLastTs, field.TypeTime, value)
	}
	if _u.mutation.LastTsCleared() {
		_spec.ClearField(alert.FieldLastTs, field.TypeTime)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.EventTable,
			Columns: []string{alert.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.EventTable,
			Columns: []string{alert.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.AssetTable,
			Columns: []string{alert.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.AssetTable,
			Columns: []string{alert.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.IncidentTable,
			Columns: []string{alert.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.IncidentTable,
			Columns: []string{alert.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlertUpdateOne is the builder for updating a single Alert entity.
type AlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertMutation
}

// SetTs sets the "ts" field.
func (_u *AlertUpdateOne) SetTs(v time.Time) *AlertUpdateOne {
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableTs(v *time.Time) *AlertUpdateOne {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *AlertUpdateOne) SetRuleID(v string) *AlertUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableRuleID(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *AlertUpdateOne) SetSeverity(v int16) *AlertUpdateOne {
	_u.mutation.ResetSeverity()
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableSeverity(v *int16) *AlertUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// AddSeverity adds value to the "severity" field.
func (_u *AlertUpdateOne) AddSeverity(v int16) *AlertUpdateOne {
	_u.mutation.AddSeverity(v)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *AlertUpdateOne) SetEventID(v uuid.UUID) *AlertUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableEventID(v *uuid.UUID) *AlertUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// ClearEventID clears the value of the "event_id" field.
func (_u *AlertUpdateOne) ClearEventID() *AlertUpdateOne {
	_u.mutation.ClearEventID()
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *AlertUpdateOne) SetAssetID(v uuid.UUID) *AlertUpdateOne {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableAssetID(v *uuid.UUID) *AlertUpdateOne {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// ClearAssetID clears the value of the "asset_id" field.
func (_u *AlertUpdateOne) ClearAssetID() *AlertUpdateOne {
	_u.mutation.ClearAssetID()
	return _u
}

// SetIncidentID sets the "incident_id" field.
func (_u *AlertUpdateOne) SetIncidentID(v uuid.UUID) *AlertUpdateOne {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableIncidentID(v *uuid.UUID) *AlertUpdateOne {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// ClearIncidentID clears the value of the "incident_id" field.
func (_u *AlertUpdateOne) ClearIncidentID() *AlertUpdateOne {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetCount sets the "count" field.
func (_u *AlertUpdateOne) SetCount(v int) *AlertUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableCount(v *int) *AlertUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *AlertUpdateOne) AddCount(v int) *AlertUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetLastTs sets the "last_ts" field.
func (_u *AlertUpdateOne) SetLastTs(v time.Time) *AlertUpdateOne {
	_u.mutation.SetLastTs(v)
	return _u
}

// SetNillableLastTs sets the "last_ts" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableLastTs(v *time.Time) *AlertUpdateOne {
	if v != nil {
		_u.SetLastTs(*v)
	}
	return _u
}

// ClearLastTs clears the value of the "last_ts" field.
func (_u *AlertUpdateOne) ClearLastTs() *AlertUpdateOne {
	_u.mutation.ClearLastTs()
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *AlertUpdateOne) SetEvent(v *Event) *AlertUpdateOne {
	return _u.SetEventID(v.ID)
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *AlertUpdateOne) SetAsset(v *Asset) *AlertUpdateOne {
	return _u.SetAssetID(v.ID)
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_u *AlertUpdateOne) SetIncident(v *Incident) *AlertUpdateOne {
	return _u.SetIncidentID(v.ID)
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdateOne) Mutation() *AlertMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *AlertUpdateOne) ClearEvent() *AlertUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *AlertUpdateOne) ClearAsset() *AlertUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// ClearIncident clears the "incident" edge to the Incident entity.
func (_u *AlertUpdateOne) ClearIncident() *AlertUpdateOne {
	_u.mutation.ClearIncident()
	return _u
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdateOne) Where(ps ...predicate.Alert) *AlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlertUpdateOne) Select(field string, fields ...string) *AlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Alert entity.
func (_u *AlertUpdateOne) Save(ctx context.Context) (*Alert, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdateOne) SaveX(ctx context.Context) *Alert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AlertUpdateOne) sqlSave(ctx context.Context) (_node *Alert, err error) {
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Alert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alert.FieldID)
		for _, f := range fields {
			if !alert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(alert.FieldTs, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(alert.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(alert.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedSeverity(); ok {
		_spec.AddField(alert.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(alert.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(alert.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastTs(); ok {
		_spec.SetField(alert.FieldLastTs, field.TypeTime, value)
	}
	if _u.mutation.LastTsCleared() {
		_spec.ClearField(alert.FieldLastTs, field.TypeTime)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.EventTable,
			Columns: []string{alert.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.EventTable,
			Columns: []string{alert.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.AssetTable,
			Columns: []string{alert.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.AssetTable,
			Columns: []string{alert.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.IncidentTable,
			Columns: []string{alert.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.IncidentTable,
			Columns: []string{alert.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Alert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
