// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"openxdr/server/ent/incident"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Alert is the model entity for the Alert schema.
type Alert struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Ts holds the value of the "ts" field.
	Ts time.Time `json:"ts,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID string `json:"rule_id,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity int16 `json:"severity,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID *uuid.UUID `json:"event_id,omitempty"`
	// AssetID holds the value of the "asset_id" field.
	AssetID *uuid.UUID `json:"asset_id,omitempty"`
	// IncidentID holds the value of the "incident_id" field.
	IncidentID *uuid.UUID `json:"incident_id,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// LastTs holds the value of the "last_ts" field.
	LastTs *time.Time `json:"last_ts,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertQuery when eager-loading is set.
	Edges        AlertEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AlertEdges holds the relations/edges for other nodes in the graph.
type AlertEdges struct {
	// Event holds the value of the event edge.
	Event *Event `json:"event,omitempty"`
	// Asset holds the value of the asset edge.
	Asset *Asset `json:"asset,omitempty"`
	// Incident holds the value of the incident edge.
	Incident *Incident `json:"incident,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertEdges) EventOrErr() (*Event, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: event.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// AssetOrErr returns the Asset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertEdges) AssetOrErr() (*Asset, error) {
	if e.Asset != nil {
		return e.Asset, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "asset"}
}

// IncidentOrErr returns the Incident value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertEdges) IncidentOrErr() (*Incident, error) {
	if e.Incident != nil {
		return e.Incident, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: incident.Label}
	}
	return nil, &NotLoadedError{edge: "incident"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Alert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alert.FieldEventID, alert.FieldAssetID, alert.FieldIncidentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case alert.FieldSeverity, alert.FieldCount:
			values[i] = new(sql.NullInt64)
		case alert.FieldRuleID:
			values[i] = new(sql.NullString)
		case alert.FieldTs, alert.FieldLastTs:
			values[i] = new(sql.NullTime)
		case alert.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Alert fields.
func (_m *Alert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alert.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case alert.FieldTs:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				_m.Ts = value.Time
			}
		case alert.FieldRuleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = value.String
			}
		case alert.FieldSeverity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = int16(value.Int64)
			}
		case alert.FieldEventID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = new(uuid.UUID)
				*_m.EventID = *value.S.(*uuid.UUID)
			}
		case alert.FieldAssetID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				_m.AssetID = new(uuid.UUID)
				*_m.AssetID = *value.S.(*uuid.UUID)
			}
		case alert.FieldIncidentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field incident_id", values[i])
			} else if value.Valid {
				_m.IncidentID = new(uuid.UUID)
				*_m.IncidentID = *value.S.(*uuid.UUID)
			}
		case alert.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		case alert.FieldLastTs:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_ts", values[i])
			} else if value.Valid {
				_m.LastTs = new(time.Time)
				*_m.LastTs = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Alert.
// This includes values selected through modifiers, order, etc.
func (_m *Alert) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the Alert entity.
func (_m *Alert) QueryEvent() *EventQuery {
	return NewAlertClient(_m.config).QueryEvent(_m)
}

// QueryAsset queries the "asset" edge of the Alert entity.
func (_m *Alert) QueryAsset() *AssetQuery {
	return NewAlertClient(_m.config).QueryAsset(_m)
}

// QueryIncident queries the "incident" edge of the Alert entity.
func (_m *Alert) QueryIncident() *IncidentQuery {
	return NewAlertClient(_m.config).QueryIncident(_m)
}

// Update returns a builder for updating this Alert.
// Note that you need to call Alert.Unwrap() before calling this method if this Alert
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Alert) Update() *AlertUpdateOne {
	return NewAlertClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Alert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Alert) Unwrap() *Alert {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Alert is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Alert) String() string {
	var builder strings.Builder
	builder.WriteString("Alert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ts=")
	builder.WriteString(_m.Ts.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("rule_id=")
	builder.WriteString(_m.RuleID)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Severity))
	builder.WriteString(", ")
	if v := _m.EventID; v != nil {
		builder.WriteString("event_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssetID; v != nil {
		builder.WriteString("asset_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IncidentID; v != nil {
		builder.WriteString("incident_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	if v := _m.LastTs; v != nil {
		builder.WriteString("last_ts=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Alerts is a parsable slice of Alert.
type Alerts []*Alert
