// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"openxdr/server/ent/incident"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AlertCreate is the builder for creating a Alert entity.
type AlertCreate struct {
	config
	mutation *AlertMutation
	hooks    []Hook
}

// SetTs sets the "ts" field.
func (_c *AlertCreate) SetTs(v time.Time) *AlertCreate {
	_c.mutation.SetTs(v)
	return _c
}

// SetRuleID sets the "rule_id" field.
func (_c *AlertCreate) SetRuleID(v string) *AlertCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *AlertCreate) SetSeverity(v int16) *AlertCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *AlertCreate) SetEventID(v uuid.UUID) *AlertCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_c *AlertCreate) SetNillableEventID(v *uuid.UUID) *AlertCreate {
	if v != nil {
		_c.SetEventID(*v)
	}
	return _c
}

// SetAssetID sets the "asset_id" field.
func (_c *AlertCreate) SetAssetID(v uuid.UUID) *AlertCreate {
	_c.mutation.SetAssetID(v)
	return _c
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_c *AlertCreate) SetNillableAssetID(v *uuid.UUID) *AlertCreate {
	if v != nil {
		_c.SetAssetID(*v)
	}
	return _c
}

// SetIncidentID sets the "incident_id" field.
func (_c *AlertCreate) SetIncidentID(v uuid.UUID) *AlertCreate {
	_c.mutation.SetIncidentID(v)
	return _c
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_c *AlertCreate) SetNillableIncidentID(v *uuid.UUID) *AlertCreate {
	if v != nil {
		_c.SetIncidentID(*v)
	}
	return _c
}

// SetCount sets the "count" field.
func (_c *AlertCreate) SetCount(v int) *AlertCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_c *AlertCreate) SetNillableCount(v *int) *AlertCreate {
	if v != nil {
		_c.SetCount(*v)
	}
	return _c
}

// SetLastTs sets the "last_ts" field.
func (_c *AlertCreate) SetLastTs(v time.Time) *AlertCreate {
	_c.mutation.SetLastTs(v)
	return _c
}

// SetNillableLastTs sets the "last_ts" field if the given value is not nil.
func (_c *AlertCreate) SetNillableLastTs(v *time.Time) *AlertCreate {
	if v != nil {
		_c.SetLastTs(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AlertCreate) SetID(v uuid.UUID) *AlertCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AlertCreate) SetNillableID(v *uuid.UUID) *AlertCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *AlertCreate) SetEvent(v *Event) *AlertCreate {
	return _c.SetEventID(v.ID)
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_c *AlertCreate) SetAsset(v *Asset) *AlertCreate {
	return _c.SetAssetID(v.ID)
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_c *AlertCreate) SetIncident(v *Incident) *AlertCreate {
	return _c.SetIncidentID(v.ID)
}

// Mutation returns the AlertMutation object of the builder.
func (_c *AlertCreate) Mutation() *AlertMutation {
	return _c.mutation
}

// Save creates the Alert in the database.
func (_c *AlertCreate) Save(ctx context.Context) (*Alert, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlertCreate) SaveX(ctx context.Context) *Alert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlertCreate) defaults() {
	if _, ok := _c.mutation.Count(); !ok {
		v := alert.DefaultCount
		_c.mutation.SetCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := alert.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlertCreate) check() error {
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "Alert.ts"`)}
	}
	if _, ok := _c.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "Alert.rule_id"`)}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "Alert.severity"`)}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Alert.count"`)}
	}
	return nil
}

func (_c *AlertCreate) sqlSave(ctx context.Context) (*Alert, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlertCreate) createSpec() (*Alert, *sqlgraph.CreateSpec) {
	var (
		_node = &Alert{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alert.Table, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(alert.FieldTs, field.TypeTime, value)
		_node.Ts = value
	}
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(alert.FieldRuleID, field.TypeString, value)
		_node.RuleID = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(alert.FieldSeverity, field.TypeInt16, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(alert.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.LastTs(); ok {
		_spec.SetField(alert.FieldLastTs, field.TypeTime, value)
		_node.LastTs = &value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.EventTable,
			Columns: []string{alert.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.AssetTable,
			Columns: []string{alert.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssetID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.IncidentTable,
			Columns: []string{alert.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IncidentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AlertCreateBulk is the builder for creating many Alert entities in bulk.
type AlertCreateBulk struct {
	config
	err      error
	builders []*AlertCreate
}

// Save creates the Alert entities in the database.
func (_c *AlertCreateBulk) Save(ctx context.Context) ([]*Alert, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Alert, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlertCreateBulk) SaveX(ctx context.Context) []*Alert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
