// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"openxdr/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks    []Hook
	mutation *AssetMutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *AssetUpdate) SetHostname(v string) *AssetUpdate {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableHostname(v *string) *AssetUpdate {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetOs sets the "os" field.
func (_u *AssetUpdate) SetOs(v string) *AssetUpdate {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableOs(v *string) *AssetUpdate {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// ClearOs clears the value of the "os" field.
func (_u *AssetUpdate) ClearOs() *AssetUpdate {
	_u.mutation.ClearOs()
	return _u
}

// SetIPAddrs sets the "ip_addrs" field.
func (_u *AssetUpdate) SetIPAddrs(v []string) *AssetUpdate {
	_u.mutation.SetIPAddrs(v)
	return _u
}

// AppendIPAddrs appends value to the "ip_addrs" field.
func (_u *AssetUpdate) AppendIPAddrs(v []string) *AssetUpdate {
	_u.mutation.AppendIPAddrs(v)
	return _u
}

// ClearIPAddrs clears the value of the "ip_addrs" field.
func (_u *AssetUpdate) ClearIPAddrs() *AssetUpdate {
	_u.mutation.ClearIPAddrs()
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AssetUpdate) SetAgentID(v uuid.UUID) *AssetUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableAgentID(v *uuid.UUID) *AssetUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *AssetUpdate) ClearAgentID() *AssetUpdate {
	_u.mutation.ClearAgentID()
	return _u
}

// SetFirstSeen sets the "first_seen" field.
func (_u *AssetUpdate) SetFirstSeen(v time.Time) *AssetUpdate {
	_u.mutation.SetFirstSeen(v)
	return _u
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableFirstSeen(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetFirstSeen(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *AssetUpdate) SetLastSeen(v time.Time) *AssetUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableLastSeen(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *AssetUpdate) AddEventIDs(ids ...uuid.UUID) *AssetUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *AssetUpdate) AddEvents(v ...*Event) *AssetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *AssetUpdate) AddAlertIDs(ids ...uuid.UUID) *AssetUpdate {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *AssetUpdate) AddAlerts(v ...*Alert) *AssetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *AssetUpdate) ClearEvents() *AssetUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *AssetUpdate) RemoveEventIDs(ids ...uuid.UUID) *AssetUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *AssetUpdate) RemoveEvents(v ...*Event) *AssetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *AssetUpdate) ClearAlerts() *AssetUpdate {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *AssetUpdate) RemoveAlertIDs(ids ...uuid.UUID) *AssetUpdate {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *AssetUpdate) RemoveAlerts(v ...*Alert) *AssetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(asset.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(asset.FieldOs, field.TypeString, value)
	}
	if _u.mutation.OsCleared() {
		_spec.ClearField(asset.FieldOs, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddrs(); ok {
		_spec.SetField(asset.FieldIPAddrs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddrs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, asset.FieldIPAddrs, value)
		})
	}
	if _u.mutation.IPAddrsCleared() {
		_spec.ClearField(asset.FieldIPAddrs, field.TypeJSON)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(asset.FieldAgentID, field.TypeUUID, value)
	}
	if _u.mutation.AgentIDCleared() {
		_spec.ClearField(asset.FieldAgentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.FirstSeen(); ok {
		_spec.SetField(asset.FieldFirstSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(asset.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.EventsTable,
			Columns: []string{asset.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.EventsTable,
			Columns: []string{asset.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.EventsTable,
			Columns: []string{asset.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AlertsTable,
			Columns: []string{asset.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AlertsTable,
			Columns: []string{asset.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AlertsTable,
			Columns: []string{asset.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetMutation
}

// SetHostname sets the "hostname" field.
func (_u *AssetUpdateOne) SetHostname(v string) *AssetUpdateOne {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableHostname(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetOs sets the "os" field.
func (_u *AssetUpdateOne) SetOs(v string) *AssetUpdateOne {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableOs(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// ClearOs clears the value of the "os" field.
func (_u *AssetUpdateOne) ClearOs() *AssetUpdateOne {
	_u.mutation.ClearOs()
	return _u
}

// SetIPAddrs sets the "ip_addrs" field.
func (_u *AssetUpdateOne) SetIPAddrs(v []string) *AssetUpdateOne {
	_u.mutation.SetIPAddrs(v)
	return _u
}

// AppendIPAddrs appends value to the "ip_addrs" field.
func (_u *AssetUpdateOne) AppendIPAddrs(v []string) *AssetUpdateOne {
	_u.mutation.AppendIPAddrs(v)
	return _u
}

// ClearIPAddrs clears the value of the "ip_addrs" field.
func (_u *AssetUpdateOne) ClearIPAddrs() *AssetUpdateOne {
	_u.mutation.ClearIPAddrs()
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AssetUpdateOne) SetAgentID(v uuid.UUID) *AssetUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableAgentID(v *uuid.UUID) *AssetUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *AssetUpdateOne) ClearAgentID() *AssetUpdateOne {
	_u.mutation.ClearAgentID()
	return _u
}

// SetFirstSeen sets the "first_seen" field.
func (_u *AssetUpdateOne) SetFirstSeen(v time.Time) *AssetUpdateOne {
	_u.mutation.SetFirstSeen(v)
	return _u
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableFirstSeen(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetFirstSeen(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *AssetUpdateOne) SetLastSeen(v time.Time) *AssetUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableLastSeen(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *AssetUpdateOne) AddEventIDs(ids ...uuid.UUID) *AssetUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *AssetUpdateOne) AddEvents(v ...*Event) *AssetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *AssetUpdateOne) AddAlertIDs(ids ...uuid.UUID) *AssetUpdateOne {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *AssetUpdateOne) AddAlerts(v ...*Alert) *AssetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *AssetUpdateOne) ClearEvents() *AssetUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *AssetUpdateOne) RemoveEventIDs(ids ...uuid.UUID) *AssetUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *AssetUpdateOne) RemoveEvents(v ...*Event) *AssetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *AssetUpdateOne) ClearAlerts() *AssetUpdateOne {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *AssetUpdateOne) RemoveAlertIDs(ids ...uuid.UUID) *AssetUpdateOne {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *AssetUpdateOne) RemoveAlerts(v ...*Alert) *AssetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(asset.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(asset.FieldOs, field.TypeString, value)
	}
	if _u.mutation.OsCleared() {
		_spec.ClearField(asset.FieldOs, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddrs(); ok {
		_spec.SetField(asset.FieldIPAddrs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddrs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, asset.FieldIPAddrs, value)
		})
	}
	if _u.mutation.IPAddrsCleared() {
		_spec.ClearField(asset.FieldIPAddrs, field.TypeJSON)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(asset.FieldAgentID, field.TypeUUID, value)
	}
	if _u.mutation.AgentIDCleared() {
		_spec.ClearField(asset.FieldAgentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.FirstSeen(); ok {
		_spec.SetField(asset.FieldFirstSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(asset.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.EventsTable,
			Columns: []string{asset.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.EventsTable,
			Columns: []string{asset.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.EventsTable,
			Columns: []string{asset.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AlertsTable,
			Columns: []string{asset.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AlertsTable,
			Columns: []string{asset.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.AlertsTable,
			Columns: []string{asset.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
