// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Event is the model entity for the Event schema.
type Event struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Ts holds the value of the "ts" field.
	Ts time.Time `json:"ts,omitempty"`
	// ClassUID holds the value of the "class_uid" field.
	ClassUID int `json:"class_uid,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// AssetID holds the value of the "asset_id" field.
	AssetID *uuid.UUID `json:"asset_id,omitempty"`
	// ProcessGUID holds the value of the "process_guid" field.
	ProcessGUID *uuid.UUID `json:"process_guid,omitempty"`
	// Username holds the value of the "username" field.
	Username *string `json:"username,omitempty"`
	// ConnTuple holds the value of the "conn_tuple" field.
	ConnTuple *string `json:"conn_tuple,omitempty"`
	// Raw holds the value of the "raw" field.
	Raw json.RawMessage `json:"raw,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventQuery when eager-loading is set.
	Edges        EventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventEdges holds the relations/edges for other nodes in the graph.
type EventEdges struct {
	// Asset holds the value of the asset edge.
	Asset *Asset `json:"asset,omitempty"`
	// Alerts holds the value of the alerts edge.
	Alerts []*Alert `json:"alerts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AssetOrErr returns the Asset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) AssetOrErr() (*Asset, error) {
	if e.Asset != nil {
		return e.Asset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "asset"}
}

// AlertsOrErr returns the Alerts value or an error if the edge
// was not loaded in eager-loading.
func (e EventEdges) AlertsOrErr() ([]*Alert, error) {
	if e.loadedTypes[1] {
		return e.Alerts, nil
	}
	return nil, &NotLoadedError{edge: "alerts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Event) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case event.FieldAssetID, event.FieldProcessGUID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case event.FieldRaw:
			values[i] = new([]byte)
		case event.FieldClassUID:
			values[i] = new(sql.NullInt64)
		case event.FieldSource, event.FieldUsername, event.FieldConnTuple:
			values[i] = new(sql.NullString)
		case event.FieldTs:
			values[i] = new(sql.NullTime)
		case event.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Event fields.
func (_m *Event) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case event.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case event.FieldTs:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				_m.Ts = value.Time
			}
		case event.FieldClassUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field class_uid", values[i])
			} else if value.Valid {
				_m.ClassUID = int(value.Int64)
			}
		case event.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case event.FieldAssetID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				_m.AssetID = new(uuid.UUID)
				*_m.AssetID = *value.S.(*uuid.UUID)
			}
		case event.FieldProcessGUID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field process_guid", values[i])
			} else if value.Valid {
				_m.ProcessGUID = new(uuid.UUID)
				*_m.ProcessGUID = *value.S.(*uuid.UUID)
			}
		case event.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = new(string)
				*_m.Username = value.String
			}
		case event.FieldConnTuple:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field conn_tuple", values[i])
			} else if value.Valid {
				_m.ConnTuple = new(string)
				*_m.ConnTuple = value.String
			}
		case event.FieldRaw:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Raw); err != nil {
					return fmt.Errorf("unmarshal field raw: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Event.
// This includes values selected through modifiers, order, etc.
func (_m *Event) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAsset queries the "asset" edge of the Event entity.
func (_m *Event) QueryAsset() *AssetQuery {
	return NewEventClient(_m.config).QueryAsset(_m)
}

// QueryAlerts queries the "alerts" edge of the Event entity.
func (_m *Event) QueryAlerts() *AlertQuery {
	return NewEventClient(_m.config).QueryAlerts(_m)
}

// Update returns a builder for updating this Event.
// Note that you need to call Event.Unwrap() before calling this method if this Event
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Event) Update() *EventUpdateOne {
	return NewEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Event entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Event) Unwrap() *Event {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Event is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Event) String() string {
	var builder strings.Builder
	builder.WriteString("Event(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ts=")
	builder.WriteString(_m.Ts.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("class_uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClassUID))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.AssetID; v != nil {
		builder.WriteString("asset_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProcessGUID; v != nil {
		builder.WriteString("process_guid=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Username; v != nil {
		builder.WriteString("username=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ConnTuple; v != nil {
		builder.WriteString("conn_tuple=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("raw=")
	builder.WriteString(fmt.Sprintf("%v", _m.Raw))
	builder.WriteByte(')')
	return builder.String()
}

// Events is a parsable slice of Event.
type Events []*Event
