// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetTs sets the "ts" field.
func (_c *EventCreate) SetTs(v time.Time) *EventCreate {
	_c.mutation.SetTs(v)
	return _c
}

// SetClassUID sets the "class_uid" field.
func (_c *EventCreate) SetClassUID(v int) *EventCreate {
	_c.mutation.SetClassUID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *EventCreate) SetSource(v string) *EventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetAssetID sets the "asset_id" field.
func (_c *EventCreate) SetAssetID(v uuid.UUID) *EventCreate {
	_c.mutation.SetAssetID(v)
	return _c
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableAssetID(v *uuid.UUID) *EventCreate {
	if v != nil {
		_c.SetAssetID(*v)
	}
	return _c
}

// SetProcessGUID sets the "process_guid" field.
func (_c *EventCreate) SetProcessGUID(v uuid.UUID) *EventCreate {
	_c.mutation.SetProcessGUID(v)
	return _c
}

// SetNillableProcessGUID sets the "process_guid" field if the given value is not nil.
func (_c *EventCreate) SetNillableProcessGUID(v *uuid.UUID) *EventCreate {
	if v != nil {
		_c.SetProcessGUID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *EventCreate) SetUsername(v string) *EventCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *EventCreate) SetNillableUsername(v *string) *EventCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetConnTuple sets the "conn_tuple" field.
func (_c *EventCreate) SetConnTuple(v string) *EventCreate {
	_c.mutation.SetConnTuple(v)
	return _c
}

// SetNillableConnTuple sets the "conn_tuple" field if the given value is not nil.
func (_c *EventCreate) SetNillableConnTuple(v *string) *EventCreate {
	if v != nil {
		_c.SetConnTuple(*v)
	}
	return _c
}

// SetRaw sets the "raw" field.
func (_c *EventCreate) SetRaw(v json.RawMessage) *EventCreate {
	_c.mutation.SetRaw(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EventCreate) SetID(v uuid.UUID) *EventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventCreate) SetNillableID(v *uuid.UUID) *EventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_c *EventCreate) SetAsset(v *Asset) *EventCreate {
	return _c.SetAssetID(v.ID)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_c *EventCreate) AddAlertIDs(ids ...uuid.UUID) *EventCreate {
	_c.mutation.AddAlertIDs(ids...)
	return _c
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_c *EventCreate) AddAlerts(v ...*Alert) *EventCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAlertIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := event.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "Event.ts"`)}
	}
	if _, ok := _c.mutation.ClassUID(); !ok {
		return &ValidationError{Name: "class_uid", err: errors.New(`ent: missing required field "Event.class_uid"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Event.source"`)}
	}
	if _, ok := _c.mutation.Raw(); !ok {
		return &ValidationError{Name: "raw", err: errors.New(`ent: missing required field "Event.raw"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(event.FieldTs, field.TypeTime, value)
		_node.Ts = value
	}
	if value, ok := _c.mutation.ClassUID(); ok {
		_spec.SetField(event.FieldClassUID, field.TypeInt, value)
		_node.ClassUID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(event.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.ProcessGUID(); ok {
		_spec.SetField(event.FieldProcessGUID, field.TypeUUID, value)
		_node.ProcessGUID = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(event.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.ConnTuple(); ok {
		_spec.SetField(event.FieldConnTuple, field.TypeString, value)
		_node.ConnTuple = &value
	}
	if value, ok := _c.mutation.Raw(); ok {
		_spec.SetField(event.FieldRaw, field.TypeJSON, value)
		_node.Raw = value
	}
	if nodes := _c.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.AssetTable,
			Columns: []string{event.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssetID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.AlertsTable,
			Columns: []string{event.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
