// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"openxdr/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTs sets the "ts" field.
func (_u *EventUpdate) SetTs(v time.Time) *EventUpdate {
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTs(v *time.Time) *EventUpdate {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// SetClassUID sets the "class_uid" field.
func (_u *EventUpdate) SetClassUID(v int) *EventUpdate {
	_u.mutation.ResetClassUID()
	_u.mutation.SetClassUID(v)
	return _u
}

// SetNillableClassUID sets the "class_uid" field if the given value is not nil.
func (_u *EventUpdate) SetNillableClassUID(v *int) *EventUpdate {
	if v != nil {
		_u.SetClassUID(*v)
	}
	return _u
}

// AddClassUID adds value to the "class_uid" field.
func (_u *EventUpdate) AddClassUID(v int) *EventUpdate {
	_u.mutation.AddClassUID(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *EventUpdate) SetSource(v string) *EventUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSource(v *string) *EventUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *EventUpdate) SetAssetID(v uuid.UUID) *EventUpdate {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableAssetID(v *uuid.UUID) *EventUpdate {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// ClearAssetID clears the value of the "asset_id" field.
func (_u *EventUpdate) ClearAssetID() *EventUpdate {
	_u.mutation.ClearAssetID()
	return _u
}

// SetProcessGUID sets the "process_guid" field.
func (_u *EventUpdate) SetProcessGUID(v uuid.UUID) *EventUpdate {
	_u.mutation.SetProcessGUID(v)
	return _u
}

// SetNillableProcessGUID sets the "process_guid" field if the given value is not nil.
func (_u *EventUpdate) SetNillableProcessGUID(v *uuid.UUID) *EventUpdate {
	if v != nil {
		_u.SetProcessGUID(*v)
	}
	return _u
}

// ClearProcessGUID clears the value of the "process_guid" field.
func (_u *EventUpdate) ClearProcessGUID() *EventUpdate {
	_u.mutation.ClearProcessGUID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *EventUpdate) SetUsername(v string) *EventUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *EventUpdate) SetNillableUsername(v *string) *EventUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *EventUpdate) ClearUsername() *EventUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetConnTuple sets the "conn_tuple" field.
func (_u *EventUpdate) SetConnTuple(v string) *EventUpdate {
	_u.mutation.SetConnTuple(v)
	return _u
}

// SetNillableConnTuple sets the "conn_tuple" field if the given value is not nil.
func (_u *EventUpdate) SetNillableConnTuple(v *string) *EventUpdate {
	if v != nil {
		_u.SetConnTuple(*v)
	}
	return _u
}

// ClearConnTuple clears the value of the "conn_tuple" field.
func (_u *EventUpdate) ClearConnTuple() *EventUpdate {
	_u.mutation.ClearConnTuple()
	return _u
}

// SetRaw sets the "raw" field.
func (_u *EventUpdate) SetRaw(v json.RawMessage) *EventUpdate {
	_u.mutation.SetRaw(v)
	return _u
}

// AppendRaw appends value to the "raw" field.
func (_u *EventUpdate) AppendRaw(v json.RawMessage) *EventUpdate {
	_u.mutation.AppendRaw(v)
	return _u
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *EventUpdate) SetAsset(v *Asset) *EventUpdate {
	return _u.SetAssetID(v.ID)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *EventUpdate) AddAlertIDs(ids ...uuid.UUID) *EventUpdate {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *EventUpdate) AddAlerts(v ...*Alert) *EventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *EventUpdate) ClearAsset() *EventUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *EventUpdate) ClearAlerts() *EventUpdate {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *EventUpdate) RemoveAlertIDs(ids ...uuid.UUID) *EventUpdate {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *EventUpdate) RemoveAlerts(v ...*Alert) *EventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(event.FieldTs, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClassUID(); ok {
		_spec.SetField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClassUID(); ok {
		_spec.AddField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(event.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessGUID(); ok {
		_spec.SetField(event.FieldProcessGUID, field.TypeUUID, value)
	}
	if _u.mutation.ProcessGUIDCleared() {
		_spec.ClearField(event.FieldProcessGUID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(event.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(event.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ConnTuple(); ok {
		_spec.SetField(event.FieldConnTuple, field.TypeString, value)
	}
	if _u.mutation.ConnTupleCleared() {
		_spec.ClearField(event.FieldConnTuple, field.TypeString)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(event.FieldRaw, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRaw(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldRaw, value)
		})
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.AssetTable,
			Columns: []string{event.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.AssetTable,
			Columns: []string{event.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.AlertsTable,
			Columns: []string{event.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.AlertsTable,
			Columns: []string{event.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.AlertsTable,
			Columns: []string{event.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetTs sets the "ts" field.
func (_u *EventUpdateOne) SetTs(v time.Time) *EventUpdateOne {
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTs(v *time.Time) *EventUpdateOne {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// SetClassUID sets the "class_uid" field.
func (_u *EventUpdateOne) SetClassUID(v int) *EventUpdateOne {
	_u.mutation.ResetClassUID()
	_u.mutation.SetClassUID(v)
	return _u
}

// SetNillableClassUID sets the "class_uid" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableClassUID(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetClassUID(*v)
	}
	return _u
}

// AddClassUID adds value to the "class_uid" field.
func (_u *EventUpdateOne) AddClassUID(v int) *EventUpdateOne {
	_u.mutation.AddClassUID(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *EventUpdateOne) SetSource(v string) *EventUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSource(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *EventUpdateOne) SetAssetID(v uuid.UUID) *EventUpdateOne {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableAssetID(v *uuid.UUID) *EventUpdateOne {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// ClearAssetID clears the value of the "asset_id" field.
func (_u *EventUpdateOne) ClearAssetID() *EventUpdateOne {
	_u.mutation.ClearAssetID()
	return _u
}

// SetProcessGUID sets the "process_guid" field.
func (_u *EventUpdateOne) SetProcessGUID(v uuid.UUID) *EventUpdateOne {
	_u.mutation.SetProcessGUID(v)
	return _u
}

// SetNillableProcessGUID sets the "process_guid" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableProcessGUID(v *uuid.UUID) *EventUpdateOne {
	if v != nil {
		_u.SetProcessGUID(*v)
	}
	return _u
}

// ClearProcessGUID clears the value of the "process_guid" field.
func (_u *EventUpdateOne) ClearProcessGUID() *EventUpdateOne {
	_u.mutation.ClearProcessGUID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *EventUpdateOne) SetUsername(v string) *EventUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableUsername(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *EventUpdateOne) ClearUsername() *EventUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetConnTuple sets the "conn_tuple" field.
func (_u *EventUpdateOne) SetConnTuple(v string) *EventUpdateOne {
	_u.mutation.SetConnTuple(v)
	return _u
}

// SetNillableConnTuple sets the "conn_tuple" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableConnTuple(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetConnTuple(*v)
	}
	return _u
}

// ClearConnTuple clears the value of the "conn_tuple" field.
func (_u *EventUpdateOne) ClearConnTuple() *EventUpdateOne {
	_u.mutation.ClearConnTuple()
	return _u
}

// SetRaw sets the "raw" field.
func (_u *EventUpdateOne) SetRaw(v json.RawMessage) *EventUpdateOne {
	_u.mutation.SetRaw(v)
	return _u
}

// AppendRaw appends value to the "raw" field.
func (_u *EventUpdateOne) AppendRaw(v json.RawMessage) *EventUpdateOne {
	_u.mutation.AppendRaw(v)
	return _u
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *EventUpdateOne) SetAsset(v *Asset) *EventUpdateOne {
	return _u.SetAssetID(v.ID)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *EventUpdateOne) AddAlertIDs(ids ...uuid.UUID) *EventUpdateOne {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *EventUpdateOne) AddAlerts(v ...*Alert) *EventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *EventUpdateOne) ClearAsset() *EventUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *EventUpdateOne) ClearAlerts() *EventUpdateOne {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *EventUpdateOne) RemoveAlertIDs(ids ...uuid.UUID) *EventUpdateOne {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *EventUpdateOne) RemoveAlerts(v ...*Alert) *EventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(event.FieldTs, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClassUID(); ok {
		_spec.SetField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClassUID(); ok {
		_spec.AddField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(event.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessGUID(); ok {
		_spec.SetField(event.FieldProcessGUID, field.TypeUUID, value)
	}
	if _u.mutation.ProcessGUIDCleared() {
		_spec.ClearField(event.FieldProcessGUID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(event.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(event.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ConnTuple(); ok {
		_spec.SetField(event.FieldConnTuple, field.TypeString, value)
	}
	if _u.mutation.ConnTupleCleared() {
		_spec.ClearField(event.FieldConnTuple, field.TypeString)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(event.FieldRaw, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRaw(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldRaw, value)
		})
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.AssetTable,
			Columns: []string{event.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.AssetTable,
			Columns: []string{event.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.AlertsTable,
			Columns: []string{event.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.AlertsTable,
			Columns: []string{event.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.AlertsTable,
			Columns: []string{event.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
