// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/incident"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// IncidentCreate is the builder for creating a Incident entity.
type IncidentCreate struct {
	config
	mutation *IncidentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *IncidentCreate) SetCreatedAt(v time.Time) *IncidentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableCreatedAt(v *time.Time) *IncidentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IncidentCreate) SetStatus(v string) *IncidentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableStatus(v *string) *IncidentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGraph sets the "graph" field.
func (_c *IncidentCreate) SetGraph(v json.RawMessage) *IncidentCreate {
	_c.mutation.SetGraph(v)
	return _c
}

// SetAiVerdict sets the "ai_verdict" field.
func (_c *IncidentCreate) SetAiVerdict(v json.RawMessage) *IncidentCreate {
	_c.mutation.SetAiVerdict(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *IncidentCreate) SetTitle(v string) *IncidentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableTitle(v *string) *IncidentCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *IncidentCreate) SetNotifiedAt(v time.Time) *IncidentCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableNotifiedAt(v *time.Time) *IncidentCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IncidentCreate) SetID(v uuid.UUID) *IncidentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableID(v *uuid.UUID) *IncidentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_c *IncidentCreate) AddAlertIDs(ids ...uuid.UUID) *IncidentCreate {
	_c.mutation.AddAlertIDs(ids...)
	return _c
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_c *IncidentCreate) AddAlerts(v ...*Alert) *IncidentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAlertIDs(ids...)
}

// Mutation returns the IncidentMutation object of the builder.
func (_c *IncidentCreate) Mutation() *IncidentMutation {
	return _c.mutation
}

// Save creates the Incident in the database.
func (_c *IncidentCreate) Save(ctx context.Context) (*Incident, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IncidentCreate) SaveX(ctx context.Context) *Incident {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IncidentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := incident.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := incident.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := incident.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IncidentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Incident.created_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Incident.status"`)}
	}
	if _, ok := _c.mutation.Graph(); !ok {
		return &ValidationError{Name: "graph", err: errors.New(`ent: missing required field "Incident.graph"`)}
	}
	return nil
}

func (_c *IncidentCreate) sqlSave(ctx context.Context) (*Incident, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IncidentCreate) createSpec() (*Incident, *sqlgraph.CreateSpec) {
	var (
		_node = &Incident{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(incident.Table, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(incident.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(incident.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Graph(); ok {
		_spec.SetField(incident.FieldGraph, field.TypeJSON, value)
		_node.Graph = value
	}
	if value, ok := _c.mutation.AiVerdict(); ok {
		_spec.SetField(incident.FieldAiVerdict, field.TypeJSON, value)
		_node.AiVerdict = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(incident.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(incident.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = &value
	}
	if nodes := _c.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.AlertsTable,
			Columns: []string{incident.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IncidentCreateBulk is the builder for creating many Incident entities in bulk.
type IncidentCreateBulk struct {
	config
	err      error
	builders []*IncidentCreate
}

// Save creates the Incident entities in the database.
func (_c *IncidentCreateBulk) Save(ctx context.Context) ([]*Incident, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Incident, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IncidentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IncidentCreateBulk) SaveX(ctx context.Context) []*Incident {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
