// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"openxdr/server/ent/alert"
	"openxdr/server/ent/incident"
	"openxdr/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// IncidentUpdate is the builder for updating Incident entities.
type IncidentUpdate struct {
	config
	hooks    []Hook
	mutation *IncidentMutation
}

// Where appends a list predicates to the IncidentUpdate builder.
func (_u *IncidentUpdate) Where(ps ...predicate.Incident) *IncidentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IncidentUpdate) SetCreatedAt(v time.Time) *IncidentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableCreatedAt(v *time.Time) *IncidentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IncidentUpdate) SetStatus(v string) *IncidentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableStatus(v *string) *IncidentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGraph sets the "graph" field.
func (_u *IncidentUpdate) SetGraph(v json.RawMessage) *IncidentUpdate {
	_u.mutation.SetGraph(v)
	return _u
}

// AppendGraph appends value to the "graph" field.
func (_u *IncidentUpdate) AppendGraph(v json.RawMessage) *IncidentUpdate {
	_u.mutation.AppendGraph(v)
	return _u
}

// SetAiVerdict sets the "ai_verdict" field.
func (_u *IncidentUpdate) SetAiVerdict(v json.RawMessage) *IncidentUpdate {
	_u.mutation.SetAiVerdict(v)
	return _u
}

// AppendAiVerdict appends value to the "ai_verdict" field.
func (_u *IncidentUpdate) AppendAiVerdict(v json.RawMessage) *IncidentUpdate {
	_u.mutation.AppendAiVerdict(v)
	return _u
}

// ClearAiVerdict clears the value of the "ai_verdict" field.
func (_u *IncidentUpdate) ClearAiVerdict() *IncidentUpdate {
	_u.mutation.ClearAiVerdict()
	return _u
}

// SetTitle sets the "title" field.
func (_u *IncidentUpdate) SetTitle(v string) *IncidentUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableTitle(v *string) *IncidentUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *IncidentUpdate) ClearTitle() *IncidentUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *IncidentUpdate) AddAlertIDs(ids ...uuid.UUID) *IncidentUpdate {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *IncidentUpdate) AddAlerts(v ...*Alert) *IncidentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the IncidentMutation object of the builder.
func (_u *IncidentUpdate) Mutation() *IncidentMutation {
	return _u.mutation
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *IncidentUpdate) ClearAlerts() *IncidentUpdate {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *IncidentUpdate) RemoveAlertIDs(ids ...uuid.UUID) *IncidentUpdate {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *IncidentUpdate) RemoveAlerts(v ...*Alert) *IncidentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IncidentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IncidentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IncidentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IncidentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IncidentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(incident.Table, incident.Columns, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(incident.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(incident.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Graph(); ok {
		_spec.SetField(incident.FieldGraph, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGraph(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, incident.FieldGraph, value)
		})
	}
	if value, ok := _u.mutation.AiVerdict(); ok {
		_spec.SetField(incident.FieldAiVerdict, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAiVerdict(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, incident.FieldAiVerdict, value)
		})
	}
	if _u.mutation.AiVerdictCleared() {
		_spec.ClearField(incident.FieldAiVerdict, field.TypeJSON)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(incident.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(incident.FieldTitle, field.TypeString)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.AlertsTable,
			Columns: []string{incident.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.AlertsTable,
			Columns: []string{incident.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.AlertsTable,
			Columns: []string{incident.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incident.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IncidentUpdateOne is the builder for updating a single Incident entity.
type IncidentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IncidentMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *IncidentUpdateOne) SetCreatedAt(v time.Time) *IncidentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableCreatedAt(v *time.Time) *IncidentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IncidentUpdateOne) SetStatus(v string) *IncidentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableStatus(v *string) *IncidentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGraph sets the "graph" field.
func (_u *IncidentUpdateOne) SetGraph(v json.RawMessage) *IncidentUpdateOne {
	_u.mutation.SetGraph(v)
	return _u
}

// AppendGraph appends value to the "graph" field.
func (_u *IncidentUpdateOne) AppendGraph(v json.RawMessage) *IncidentUpdateOne {
	_u.mutation.AppendGraph(v)
	return _u
}

// SetAiVerdict sets the "ai_verdict" field.
func (_u *IncidentUpdateOne) SetAiVerdict(v json.RawMessage) *IncidentUpdateOne {
	_u.mutation.SetAiVerdict(v)
	return _u
}

// AppendAiVerdict appends value to the "ai_verdict" field.
func (_u *IncidentUpdateOne) AppendAiVerdict(v json.RawMessage) *IncidentUpdateOne {
	_u.mutation.AppendAiVerdict(v)
	return _u
}

// ClearAiVerdict clears the value of the "ai_verdict" field.
func (_u *IncidentUpdateOne) ClearAiVerdict() *IncidentUpdateOne {
	_u.mutation.ClearAiVerdict()
	return _u
}

// SetTitle sets the "title" field.
func (_u *IncidentUpdateOne) SetTitle(v string) *IncidentUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableTitle(v *string) *IncidentUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *IncidentUpdateOne) ClearTitle() *IncidentUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (_u *IncidentUpdateOne) AddAlertIDs(ids ...uuid.UUID) *IncidentUpdateOne {
	_u.mutation.AddAlertIDs(ids...)
	return _u
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (_u *IncidentUpdateOne) AddAlerts(v ...*Alert) *IncidentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertIDs(ids...)
}

// Mutation returns the IncidentMutation object of the builder.
func (_u *IncidentUpdateOne) Mutation() *IncidentMutation {
	return _u.mutation
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (_u *IncidentUpdateOne) ClearAlerts() *IncidentUpdateOne {
	_u.mutation.ClearAlerts()
	return _u
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (_u *IncidentUpdateOne) RemoveAlertIDs(ids ...uuid.UUID) *IncidentUpdateOne {
	_u.mutation.RemoveAlertIDs(ids...)
	return _u
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (_u *IncidentUpdateOne) RemoveAlerts(v ...*Alert) *IncidentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertIDs(ids...)
}

// Where appends a list predicates to the IncidentUpdate builder.
func (_u *IncidentUpdateOne) Where(ps ...predicate.Incident) *IncidentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IncidentUpdateOne) Select(field string, fields ...string) *IncidentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Incident entity.
func (_u *IncidentUpdateOne) Save(ctx context.Context) (*Incident, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IncidentUpdateOne) SaveX(ctx context.Context) *Incident {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IncidentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IncidentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IncidentUpdateOne) sqlSave(ctx context.Context) (_node *Incident, err error) {
	_spec := sqlgraph.NewUpdateSpec(incident.Table, incident.Columns, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Incident.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incident.FieldID)
		for _, f := range fields {
			if !incident.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != incident.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(incident.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(incident.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Graph(); ok {
		_spec.SetField(incident.FieldGraph, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGraph(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, incident.FieldGraph, value)
		})
	}
	if value, ok := _u.mutation.AiVerdict(); ok {
		_spec.SetField(incident.FieldAiVerdict, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAiVerdict(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, incident.FieldAiVerdict, value)
		})
	}
	if _u.mutation.AiVerdictCleared() {
		_spec.ClearField(incident.FieldAiVerdict, field.TypeJSON)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(incident.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(incident.FieldTitle, field.TypeString)
	}
	if _u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.AlertsTable,
			Columns: []string{incident.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !_u.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.AlertsTable,
			Columns: []string{incident.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.AlertsTable,
			Columns: []string{incident.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Incident{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incident.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
