// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"openxdr/server/ent/intel"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Intel is the model entity for the Intel schema.
type Intel struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind intel.Kind `json:"kind,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity int16 `json:"severity,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// MatchedCount holds the value of the "matched_count" field.
	MatchedCount int `json:"matched_count,omitempty"`
	// LastMatchedAt holds the value of the "last_matched_at" field.
	LastMatchedAt *time.Time `json:"last_matched_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Intel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case intel.FieldSeverity, intel.FieldMatchedCount:
			values[i] = new(sql.NullInt64)
		case intel.FieldKind, intel.FieldValue, intel.FieldSource, intel.FieldNote:
			values[i] = new(sql.NullString)
		case intel.FieldCreatedAt, intel.FieldExpiresAt, intel.FieldLastMatchedAt:
			values[i] = new(sql.NullTime)
		case intel.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Intel fields.
func (_m *Intel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case intel.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case intel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case intel.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = intel.Kind(value.String)
			}
		case intel.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case intel.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case intel.FieldSeverity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = int16(value.Int64)
			}
		case intel.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case intel.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case intel.FieldMatchedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field matched_count", values[i])
			} else if value.Valid {
				_m.MatchedCount = int(value.Int64)
			}
		case intel.FieldLastMatchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_matched_at", values[i])
			} else if value.Valid {
				_m.LastMatchedAt = new(time.Time)
				*_m.LastMatchedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the Intel.
// This includes values selected through modifiers, order, etc.
func (_m *Intel) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Intel.
// Note that you need to call Intel.Unwrap() before calling this method if this Intel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Intel) Update() *IntelUpdateOne {
	return NewIntelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Intel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Intel) Unwrap() *Intel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Intel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Intel) String() string {
	var builder strings.Builder
	builder.WriteString("Intel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Severity))
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("matched_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MatchedCount))
	builder.WriteString(", ")
	if v := _m.LastMatchedAt; v != nil {
		builder.WriteString("last_matched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Intels is a parsable slice of Intel.
type Intels []*Intel
