// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openxdr/server/ent/intel"
	"openxdr/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IntelUpdate is the builder for updating Intel entities.
type IntelUpdate struct {
	config
	hooks    []Hook
	mutation *IntelMutation
}

// Where appends a list predicates to the IntelUpdate builder.
func (_u *IntelUpdate) Where(ps ...predicate.Intel) *IntelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IntelUpdate) SetCreatedAt(v time.Time) *IntelUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableCreatedAt(v *time.Time) *IntelUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *IntelUpdate) SetKind(v intel.Kind) *IntelUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableKind(v *intel.Kind) *IntelUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *IntelUpdate) SetValue(v string) *IntelUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableValue(v *string) *IntelUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *IntelUpdate) SetSource(v string) *IntelUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableSource(v *string) *IntelUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *IntelUpdate) SetSeverity(v int16) *IntelUpdate {
	_u.mutation.ResetSeverity()
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableSeverity(v *int16) *IntelUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// AddSeverity adds value to the "severity" field.
func (_u *IntelUpdate) AddSeverity(v int16) *IntelUpdate {
	_u.mutation.AddSeverity(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *IntelUpdate) SetNote(v string) *IntelUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableNote(v *string) *IntelUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *IntelUpdate) ClearNote() *IntelUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IntelUpdate) SetExpiresAt(v time.Time) *IntelUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableExpiresAt(v *time.Time) *IntelUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *IntelUpdate) ClearExpiresAt() *IntelUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMatchedCount sets the "matched_count" field.
func (_u *IntelUpdate) SetMatchedCount(v int) *IntelUpdate {
	_u.mutation.ResetMatchedCount()
	_u.mutation.SetMatchedCount(v)
	return _u
}

// SetNillableMatchedCount sets the "matched_count" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableMatchedCount(v *int) *IntelUpdate {
	if v != nil {
		_u.SetMatchedCount(*v)
	}
	return _u
}

// AddMatchedCount adds value to the "matched_count" field.
func (_u *IntelUpdate) AddMatchedCount(v int) *IntelUpdate {
	_u.mutation.AddMatchedCount(v)
	return _u
}

// SetLastMatchedAt sets the "last_matched_at" field.
func (_u *IntelUpdate) SetLastMatchedAt(v time.Time) *IntelUpdate {
	_u.mutation.SetLastMatchedAt(v)
	return _u
}

// SetNillableLastMatchedAt sets the "last_matched_at" field if the given value is not nil.
func (_u *IntelUpdate) SetNillableLastMatchedAt(v *time.Time) *IntelUpdate {
	if v != nil {
		_u.SetLastMatchedAt(*v)
	}
	return _u
}

// ClearLastMatchedAt clears the value of the "last_matched_at" field.
func (_u *IntelUpdate) ClearLastMatchedAt() *IntelUpdate {
	_u.mutation.ClearLastMatchedAt()
	return _u
}

// Mutation returns the IntelMutation object of the builder.
func (_u *IntelUpdate) Mutation() *IntelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntelUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := intel.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Intel.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *IntelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intel.Table, intel.Columns, sqlgraph.NewFieldSpec(intel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(intel.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(intel.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(intel.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(intel.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(intel.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedSeverity(); ok {
		_spec.AddField(intel.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(intel.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(intel.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(intel.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(intel.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MatchedCount(); ok {
		_spec.SetField(intel.FieldMatchedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchedCount(); ok {
		_spec.AddField(intel.FieldMatchedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMatchedAt(); ok {
		_spec.SetField(intel.FieldLastMatchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastMatchedAtCleared() {
		_spec.ClearField(intel.FieldLastMatchedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntelUpdateOne is the builder for updating a single Intel entity.
type IntelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntelMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *IntelUpdateOne) SetCreatedAt(v time.Time) *IntelUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableCreatedAt(v *time.Time) *IntelUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *IntelUpdateOne) SetKind(v intel.Kind) *IntelUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableKind(v *intel.Kind) *IntelUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *IntelUpdateOne) SetValue(v string) *IntelUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableValue(v *string) *IntelUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *IntelUpdateOne) SetSource(v string) *IntelUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableSource(v *string) *IntelUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *IntelUpdateOne) SetSeverity(v int16) *IntelUpdateOne {
	_u.mutation.ResetSeverity()
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableSeverity(v *int16) *IntelUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// AddSeverity adds value to the "severity" field.
func (_u *IntelUpdateOne) AddSeverity(v int16) *IntelUpdateOne {
	_u.mutation.AddSeverity(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *IntelUpdateOne) SetNote(v string) *IntelUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableNote(v *string) *IntelUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *IntelUpdateOne) ClearNote() *IntelUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *IntelUpdateOne) SetExpiresAt(v time.Time) *IntelUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableExpiresAt(v *time.Time) *IntelUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *IntelUpdateOne) ClearExpiresAt() *IntelUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMatchedCount sets the "matched_count" field.
func (_u *IntelUpdateOne) SetMatchedCount(v int) *IntelUpdateOne {
	_u.mutation.ResetMatchedCount()
	_u.mutation.SetMatchedCount(v)
	return _u
}

// SetNillableMatchedCount sets the "matched_count" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableMatchedCount(v *int) *IntelUpdateOne {
	if v != nil {
		_u.SetMatchedCount(*v)
	}
	return _u
}

// AddMatchedCount adds value to the "matched_count" field.
func (_u *IntelUpdateOne) AddMatchedCount(v int) *IntelUpdateOne {
	_u.mutation.AddMatchedCount(v)
	return _u
}

// SetLastMatchedAt sets the "last_matched_at" field.
func (_u *IntelUpdateOne) SetLastMatchedAt(v time.Time) *IntelUpdateOne {
	_u.mutation.SetLastMatchedAt(v)
	return _u
}

// SetNillableLastMatchedAt sets the "last_matched_at" field if the given value is not nil.
func (_u *IntelUpdateOne) SetNillableLastMatchedAt(v *time.Time) *IntelUpdateOne {
	if v != nil {
		_u.SetLastMatchedAt(*v)
	}
	return _u
}

// ClearLastMatchedAt clears the value of the "last_matched_at" field.
func (_u *IntelUpdateOne) ClearLastMatchedAt() *IntelUpdateOne {
	_u.mutation.ClearLastMatchedAt()
	return _u
}

// Mutation returns the IntelMutation object of the builder.
func (_u *IntelUpdateOne) Mutation() *IntelMutation {
	return _u.mutation
}

// Where appends a list predicates to the IntelUpdate builder.
func (_u *IntelUpdateOne) Where(ps ...predicate.Intel) *IntelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntelUpdateOne) Select(field string, fields ...string) *IntelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Intel entity.
func (_u *IntelUpdateOne) Save(ctx context.Context) (*Intel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntelUpdateOne) SaveX(ctx context.Context) *Intel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntelUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := intel.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Intel.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *IntelUpdateOne) sqlSave(ctx context.Context) (_node *Intel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intel.Table, intel.Columns, sqlgraph.NewFieldSpec(intel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Intel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, intel.FieldID)
		for _, f := range fields {
			if !intel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != intel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(intel.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(intel.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(intel.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(intel.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(intel.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedSeverity(); ok {
		_spec.AddField(intel.FieldSeverity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(intel.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(intel.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(intel.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(intel.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MatchedCount(); ok {
		_spec.SetField(intel.FieldMatchedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMatchedCount(); ok {
		_spec.AddField(intel.FieldMatchedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastMatchedAt(); ok {
		_spec.SetField(intel.FieldLastMatchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastMatchedAtCleared() {
		_spec.ClearField(intel.FieldLastMatchedAt, field.TypeTime)
	}
	_node = &Intel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
