// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openxdr/server/ent/predicate"
	"openxdr/server/ent/processbaseline"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProcessBaselineUpdate is the builder for updating ProcessBaseline entities.
type ProcessBaselineUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessBaselineMutation
}

// Where appends a list predicates to the ProcessBaselineUpdate builder.
func (_u *ProcessBaselineUpdate) Where(ps ...predicate.ProcessBaseline) *ProcessBaselineUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *ProcessBaselineUpdate) SetAssetID(v uuid.UUID) *ProcessBaselineUpdate {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *ProcessBaselineUpdate) SetNillableAssetID(v *uuid.UUID) *ProcessBaselineUpdate {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetExePath sets the "exe_path" field.
func (_u *ProcessBaselineUpdate) SetExePath(v string) *ProcessBaselineUpdate {
	_u.mutation.SetExePath(v)
	return _u
}

// SetNillableExePath sets the "exe_path" field if the given value is not nil.
func (_u *ProcessBaselineUpdate) SetNillableExePath(v *string) *ProcessBaselineUpdate {
	if v != nil {
		_u.SetExePath(*v)
	}
	return _u
}

// SetFirstSeen sets the "first_seen" field.
func (_u *ProcessBaselineUpdate) SetFirstSeen(v time.Time) *ProcessBaselineUpdate {
	_u.mutation.SetFirstSeen(v)
	return _u
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_u *ProcessBaselineUpdate) SetNillableFirstSeen(v *time.Time) *ProcessBaselineUpdate {
	if v != nil {
		_u.SetFirstSeen(*v)
	}
	return _u
}

// Mutation returns the ProcessBaselineMutation object of the builder.
func (_u *ProcessBaselineUpdate) Mutation() *ProcessBaselineMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProcessBaselineUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessBaselineUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProcessBaselineUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessBaselineUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProcessBaselineUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(processbaseline.Table, processbaseline.Columns, sqlgraph.NewFieldSpec(processbaseline.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetID(); ok {
		_spec.SetField(processbaseline.FieldAssetID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExePath(); ok {
		_spec.SetField(processbaseline.FieldExePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstSeen(); ok {
		_spec.SetField(processbaseline.FieldFirstSeen, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processbaseline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProcessBaselineUpdateOne is the builder for updating a single ProcessBaseline entity.
type ProcessBaselineUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessBaselineMutation
}

// SetAssetID sets the "asset_id" field.
func (_u *ProcessBaselineUpdateOne) SetAssetID(v uuid.UUID) *ProcessBaselineUpdateOne {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *ProcessBaselineUpdateOne) SetNillableAssetID(v *uuid.UUID) *ProcessBaselineUpdateOne {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetExePath sets the "exe_path" field.
func (_u *ProcessBaselineUpdateOne) SetExePath(v string) *ProcessBaselineUpdateOne {
	_u.mutation.SetExePath(v)
	return _u
}

// SetNillableExePath sets the "exe_path" field if the given value is not nil.
func (_u *ProcessBaselineUpdateOne) SetNillableExePath(v *string) *ProcessBaselineUpdateOne {
	if v != nil {
		_u.SetExePath(*v)
	}
	return _u
}

// SetFirstSeen sets the "first_seen" field.
func (_u *ProcessBaselineUpdateOne) SetFirstSeen(v time.Time) *ProcessBaselineUpdateOne {
	_u.mutation.SetFirstSeen(v)
	return _u
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_u *ProcessBaselineUpdateOne) SetNillableFirstSeen(v *time.Time) *ProcessBaselineUpdateOne {
	if v != nil {
		_u.SetFirstSeen(*v)
	}
	return _u
}

// Mutation returns the ProcessBaselineMutation object of the builder.
func (_u *ProcessBaselineUpdateOne) Mutation() *ProcessBaselineMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProcessBaselineUpdate builder.
func (_u *ProcessBaselineUpdateOne) Where(ps ...predicate.ProcessBaseline) *ProcessBaselineUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProcessBaselineUpdateOne) Select(field string, fields ...string) *ProcessBaselineUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProcessBaseline entity.
func (_u *ProcessBaselineUpdateOne) Save(ctx context.Context) (*ProcessBaseline, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessBaselineUpdateOne) SaveX(ctx context.Context) *ProcessBaseline {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProcessBaselineUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessBaselineUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProcessBaselineUpdateOne) sqlSave(ctx context.Context) (_node *ProcessBaseline, err error) {
	_spec := sqlgraph.NewUpdateSpec(processbaseline.Table, processbaseline.Columns, sqlgraph.NewFieldSpec(processbaseline.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProcessBaseline.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processbaseline.FieldID)
		for _, f := range fields {
			if !processbaseline.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != processbaseline.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetID(); ok {
		_spec.SetField(processbaseline.FieldAssetID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExePath(); ok {
		_spec.SetField(processbaseline.FieldExePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstSeen(); ok {
		_spec.SetField(processbaseline.FieldFirstSeen, field.TypeTime, value)
	}
	_node = &ProcessBaseline{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processbaseline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
