// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"openxdr/server/ent/predicate"
	"openxdr/server/ent/processbaseline"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProcessBaselineDelete is the builder for deleting a ProcessBaseline entity.
type ProcessBaselineDelete struct {
	config
	hooks    []Hook
	mutation *ProcessBaselineMutation
}

// Where appends a list predicates to the ProcessBaselineDelete builder.
func (_d *ProcessBaselineDelete) Where(ps ...predicate.ProcessBaseline) *ProcessBaselineDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProcessBaselineDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProcessBaselineDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProcessBaselineDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(processbaseline.Table, sqlgraph.NewFieldSpec(processbaseline.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProcessBaselineDeleteOne is the builder for deleting a single ProcessBaseline entity.
type ProcessBaselineDeleteOne struct {
	_d *ProcessBaselineDelete
}

// Where appends a list predicates to the ProcessBaselineDelete builder.
func (_d *ProcessBaselineDeleteOne) Where(ps ...predicate.ProcessBaseline) *ProcessBaselineDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProcessBaselineDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{processbaseline.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProcessBaselineDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
