// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openxdr/server/ent/processbaseline"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProcessBaselineCreate is the builder for creating a ProcessBaseline entity.
type ProcessBaselineCreate struct {
	config
	mutation *ProcessBaselineMutation
	hooks    []Hook
}

// SetAssetID sets the "asset_id" field.
func (_c *ProcessBaselineCreate) SetAssetID(v uuid.UUID) *ProcessBaselineCreate {
	_c.mutation.SetAssetID(v)
	return _c
}

// SetExePath sets the "exe_path" field.
func (_c *ProcessBaselineCreate) SetExePath(v string) *ProcessBaselineCreate {
	_c.mutation.SetExePath(v)
	return _c
}

// SetFirstSeen sets the "first_seen" field.
func (_c *ProcessBaselineCreate) SetFirstSeen(v time.Time) *ProcessBaselineCreate {
	_c.mutation.SetFirstSeen(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ProcessBaselineCreate) SetID(v uuid.UUID) *ProcessBaselineCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProcessBaselineCreate) SetNillableID(v *uuid.UUID) *ProcessBaselineCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ProcessBaselineMutation object of the builder.
func (_c *ProcessBaselineCreate) Mutation() *ProcessBaselineMutation {
	return _c.mutation
}

// Save creates the ProcessBaseline in the database.
func (_c *ProcessBaselineCreate) Save(ctx context.Context) (*ProcessBaseline, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProcessBaselineCreate) SaveX(ctx context.Context) *ProcessBaseline {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessBaselineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessBaselineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProcessBaselineCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := processbaseline.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProcessBaselineCreate) check() error {
	if _, ok := _c.mutation.AssetID(); !ok {
		return &ValidationError{Name: "asset_id", err: errors.New(`ent: missing required field "ProcessBaseline.asset_id"`)}
	}
	if _, ok := _c.mutation.ExePath(); !ok {
		return &ValidationError{Name: "exe_path", err: errors.New(`ent: missing required field "ProcessBaseline.exe_path"`)}
	}
	if _, ok := _c.mutation.FirstSeen(); !ok {
		return &ValidationError{Name: "first_seen", err: errors.New(`ent: missing required field "ProcessBaseline.first_seen"`)}
	}
	return nil
}

func (_c *ProcessBaselineCreate) sqlSave(ctx context.Context) (*ProcessBaseline, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProcessBaselineCreate) createSpec() (*ProcessBaseline, *sqlgraph.CreateSpec) {
	var (
		_node = &ProcessBaseline{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(processbaseline.Table, sqlgraph.NewFieldSpec(processbaseline.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AssetID(); ok {
		_spec.SetField(processbaseline.FieldAssetID, field.TypeUUID, value)
		_node.AssetID = value
	}
	if value, ok := _c.mutation.ExePath(); ok {
		_spec.SetField(processbaseline.FieldExePath, field.TypeString, value)
		_node.ExePath = value
	}
	if value, ok := _c.mutation.FirstSeen(); ok {
		_spec.SetField(processbaseline.FieldFirstSeen, field.TypeTime, value)
		_node.FirstSeen = value
	}
	return _node, _spec
}

// ProcessBaselineCreateBulk is the builder for creating many ProcessBaseline entities in bulk.
type ProcessBaselineCreateBulk struct {
	config
	err      error
	builders []*ProcessBaselineCreate
}

// Save creates the ProcessBaseline entities in the database.
func (_c *ProcessBaselineCreateBulk) Save(ctx context.Context) ([]*ProcessBaseline, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProcessBaseline, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProcessBaselineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProcessBaselineCreateBulk) SaveX(ctx context.Context) []*ProcessBaseline {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessBaselineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessBaselineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
