// Code generated by ent, DO NOT EDIT.

package ent

import (
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/auditlog"
	"openxdr/server/ent/command"
	"openxdr/server/ent/event"
	"openxdr/server/ent/incident"
	"openxdr/server/ent/intel"
	"openxdr/server/ent/schema"
	"openxdr/server/ent/session"
	"openxdr/server/ent/suppression"
	"openxdr/server/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alertFields := schema.Alert{}.Fields()
	_ = alertFields
	// alertDescCount is the schema descriptor for count field.
	alertDescCount := alertFields[7].Descriptor()
	// alert.DefaultCount holds the default value on creation for the count field.
	alert.DefaultCount = alertDescCount.Default.(int)
	// alertDescID is the schema descriptor for id field.
	alertDescID := alertFields[0].Descriptor()
	// alert.DefaultID holds the default value on creation for the id field.
	alert.DefaultID = alertDescID.Default.(func() uuid.UUID)
	assetFields := schema.Asset{}.Fields()
	_ = assetFields
	// assetDescFirstSeen is the schema descriptor for first_seen field.
	assetDescFirstSeen := assetFields[5].Descriptor()
	// asset.DefaultFirstSeen holds the default value on creation for the first_seen field.
	asset.DefaultFirstSeen = assetDescFirstSeen.Default.(func() time.Time)
	// assetDescLastSeen is the schema descriptor for last_seen field.
	assetDescLastSeen := assetFields[6].Descriptor()
	// asset.DefaultLastSeen holds the default value on creation for the last_seen field.
	asset.DefaultLastSeen = assetDescLastSeen.Default.(func() time.Time)
	// assetDescID is the schema descriptor for id field.
	assetDescID := assetFields[0].Descriptor()
	// asset.DefaultID holds the default value on creation for the id field.
	asset.DefaultID = assetDescID.Default.(func() uuid.UUID)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescTs is the schema descriptor for ts field.
	auditlogDescTs := auditlogFields[1].Descriptor()
	// auditlog.DefaultTs holds the default value on creation for the ts field.
	auditlog.DefaultTs = auditlogDescTs.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	commandFields := schema.Command{}.Fields()
	_ = commandFields
	// commandDescCreatedAt is the schema descriptor for created_at field.
	commandDescCreatedAt := commandFields[1].Descriptor()
	// command.DefaultCreatedAt holds the default value on creation for the created_at field.
	command.DefaultCreatedAt = commandDescCreatedAt.Default.(func() time.Time)
	// commandDescStatus is the schema descriptor for status field.
	commandDescStatus := commandFields[3].Descriptor()
	// command.DefaultStatus holds the default value on creation for the status field.
	command.DefaultStatus = commandDescStatus.Default.(string)
	// commandDescDryRun is the schema descriptor for dry_run field.
	commandDescDryRun := commandFields[4].Descriptor()
	// command.DefaultDryRun holds the default value on creation for the dry_run field.
	command.DefaultDryRun = commandDescDryRun.Default.(bool)
	// commandDescIssuedBy is the schema descriptor for issued_by field.
	commandDescIssuedBy := commandFields[8].Descriptor()
	// command.DefaultIssuedBy holds the default value on creation for the issued_by field.
	command.DefaultIssuedBy = commandDescIssuedBy.Default.(string)
	// commandDescID is the schema descriptor for id field.
	commandDescID := commandFields[0].Descriptor()
	// command.DefaultID holds the default value on creation for the id field.
	command.DefaultID = commandDescID.Default.(func() uuid.UUID)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
	incidentFields := schema.Incident{}.Fields()
	_ = incidentFields
	// incidentDescCreatedAt is the schema descriptor for created_at field.
	incidentDescCreatedAt := incidentFields[1].Descriptor()
	// incident.DefaultCreatedAt holds the default value on creation for the created_at field.
	incident.DefaultCreatedAt = incidentDescCreatedAt.Default.(func() time.Time)
	// incidentDescStatus is the schema descriptor for status field.
	incidentDescStatus := incidentFields[2].Descriptor()
	// incident.DefaultStatus holds the default value on creation for the status field.
	incident.DefaultStatus = incidentDescStatus.Default.(string)
	// incidentDescID is the schema descriptor for id field.
	incidentDescID := incidentFields[0].Descriptor()
	// incident.DefaultID holds the default value on creation for the id field.
	incident.DefaultID = incidentDescID.Default.(func() uuid.UUID)
	intelFields := schema.Intel{}.Fields()
	_ = intelFields
	// intelDescCreatedAt is the schema descriptor for created_at field.
	intelDescCreatedAt := intelFields[1].Descriptor()
	// intel.DefaultCreatedAt holds the default value on creation for the created_at field.
	intel.DefaultCreatedAt = intelDescCreatedAt.Default.(func() time.Time)
	// intelDescSource is the schema descriptor for source field.
	intelDescSource := intelFields[4].Descriptor()
	// intel.DefaultSource holds the default value on creation for the source field.
	intel.DefaultSource = intelDescSource.Default.(string)
	// intelDescSeverity is the schema descriptor for severity field.
	intelDescSeverity := intelFields[5].Descriptor()
	// intel.DefaultSeverity holds the default value on creation for the severity field.
	intel.DefaultSeverity = intelDescSeverity.Default.(int16)
	// intelDescMatchedCount is the schema descriptor for matched_count field.
	intelDescMatchedCount := intelFields[8].Descriptor()
	// intel.DefaultMatchedCount holds the default value on creation for the matched_count field.
	intel.DefaultMatchedCount = intelDescMatchedCount.Default.(int)
	// intelDescID is the schema descriptor for id field.
	intelDescID := intelFields[0].Descriptor()
	// intel.DefaultID holds the default value on creation for the id field.
	intel.DefaultID = intelDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[1].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	suppressionFields := schema.Suppression{}.Fields()
	_ = suppressionFields
	// suppressionDescCreatedAt is the schema descriptor for created_at field.
	suppressionDescCreatedAt := suppressionFields[1].Descriptor()
	// suppression.DefaultCreatedAt holds the default value on creation for the created_at field.
	suppression.DefaultCreatedAt = suppressionDescCreatedAt.Default.(func() time.Time)
	// suppressionDescCreatedBy is the schema descriptor for created_by field.
	suppressionDescCreatedBy := suppressionFields[5].Descriptor()
	// suppression.DefaultCreatedBy holds the default value on creation for the created_by field.
	suppression.DefaultCreatedBy = suppressionDescCreatedBy.Default.(string)
	// suppressionDescMatchedCount is the schema descriptor for matched_count field.
	suppressionDescMatchedCount := suppressionFields[7].Descriptor()
	// suppression.DefaultMatchedCount holds the default value on creation for the matched_count field.
	suppression.DefaultMatchedCount = suppressionDescMatchedCount.Default.(int)
	// suppressionDescID is the schema descriptor for id field.
	suppressionDescID := suppressionFields[0].Descriptor()
	// suppression.DefaultID holds the default value on creation for the id field.
	suppression.DefaultID = suppressionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
