// Code generated by ent, DO NOT EDIT.

package ent

import (
	"openxdr/server/ent/alert"
	"openxdr/server/ent/asset"
	"openxdr/server/ent/event"
	"openxdr/server/ent/incident"
	"openxdr/server/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alertFields := schema.Alert{}.Fields()
	_ = alertFields
	// alertDescCount is the schema descriptor for count field.
	alertDescCount := alertFields[7].Descriptor()
	// alert.DefaultCount holds the default value on creation for the count field.
	alert.DefaultCount = alertDescCount.Default.(int)
	// alertDescID is the schema descriptor for id field.
	alertDescID := alertFields[0].Descriptor()
	// alert.DefaultID holds the default value on creation for the id field.
	alert.DefaultID = alertDescID.Default.(func() uuid.UUID)
	assetFields := schema.Asset{}.Fields()
	_ = assetFields
	// assetDescFirstSeen is the schema descriptor for first_seen field.
	assetDescFirstSeen := assetFields[5].Descriptor()
	// asset.DefaultFirstSeen holds the default value on creation for the first_seen field.
	asset.DefaultFirstSeen = assetDescFirstSeen.Default.(func() time.Time)
	// assetDescLastSeen is the schema descriptor for last_seen field.
	assetDescLastSeen := assetFields[6].Descriptor()
	// asset.DefaultLastSeen holds the default value on creation for the last_seen field.
	asset.DefaultLastSeen = assetDescLastSeen.Default.(func() time.Time)
	// assetDescID is the schema descriptor for id field.
	assetDescID := assetFields[0].Descriptor()
	// asset.DefaultID holds the default value on creation for the id field.
	asset.DefaultID = assetDescID.Default.(func() uuid.UUID)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
	incidentFields := schema.Incident{}.Fields()
	_ = incidentFields
	// incidentDescCreatedAt is the schema descriptor for created_at field.
	incidentDescCreatedAt := incidentFields[1].Descriptor()
	// incident.DefaultCreatedAt holds the default value on creation for the created_at field.
	incident.DefaultCreatedAt = incidentDescCreatedAt.Default.(func() time.Time)
	// incidentDescStatus is the schema descriptor for status field.
	incidentDescStatus := incidentFields[2].Descriptor()
	// incident.DefaultStatus holds the default value on creation for the status field.
	incident.DefaultStatus = incidentDescStatus.Default.(string)
	// incidentDescID is the schema descriptor for id field.
	incidentDescID := incidentFields[0].Descriptor()
	// incident.DefaultID holds the default value on creation for the id field.
	incident.DefaultID = incidentDescID.Default.(func() uuid.UUID)
}
