// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"openxdr/server/ent/predicate"
	"openxdr/server/ent/suppression"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SuppressionDelete is the builder for deleting a Suppression entity.
type SuppressionDelete struct {
	config
	hooks    []Hook
	mutation *SuppressionMutation
}

// Where appends a list predicates to the SuppressionDelete builder.
func (_d *SuppressionDelete) Where(ps ...predicate.Suppression) *SuppressionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SuppressionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SuppressionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SuppressionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(suppression.Table, sqlgraph.NewFieldSpec(suppression.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SuppressionDeleteOne is the builder for deleting a single Suppression entity.
type SuppressionDeleteOne struct {
	_d *SuppressionDelete
}

// Where appends a list predicates to the SuppressionDelete builder.
func (_d *SuppressionDeleteOne) Where(ps ...predicate.Suppression) *SuppressionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SuppressionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{suppression.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SuppressionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
