// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"openxdr/server/ent/suppression"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Suppression is the model entity for the Suppression schema.
type Suppression struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID string `json:"rule_id,omitempty"`
	// AssetID holds the value of the "asset_id" field.
	AssetID *uuid.UUID `json:"asset_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// MatchedCount holds the value of the "matched_count" field.
	MatchedCount int `json:"matched_count,omitempty"`
	// LastMatchedAt holds the value of the "last_matched_at" field.
	LastMatchedAt *time.Time `json:"last_matched_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Suppression) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case suppression.FieldAssetID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case suppression.FieldMatchedCount:
			values[i] = new(sql.NullInt64)
		case suppression.FieldRuleID, suppression.FieldReason, suppression.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case suppression.FieldCreatedAt, suppression.FieldExpiresAt, suppression.FieldLastMatchedAt:
			values[i] = new(sql.NullTime)
		case suppression.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Suppression fields.
func (_m *Suppression) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case suppression.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case suppression.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case suppression.FieldRuleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = value.String
			}
		case suppression.FieldAssetID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				_m.AssetID = new(uuid.UUID)
				*_m.AssetID = *value.S.(*uuid.UUID)
			}
		case suppression.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case suppression.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case suppression.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case suppression.FieldMatchedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field matched_count", values[i])
			} else if value.Valid {
				_m.MatchedCount = int(value.Int64)
			}
		case suppression.FieldLastMatchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_matched_at", values[i])
			} else if value.Valid {
				_m.LastMatchedAt = new(time.Time)
				*_m.LastMatchedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Suppression.
// This includes values selected through modifiers, order, etc.
func (_m *Suppression) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Suppression.
// Note that you need to call Suppression.Unwrap() before calling this method if this Suppression
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Suppression) Update() *SuppressionUpdateOne {
	return NewSuppressionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Suppression entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Suppression) Unwrap() *Suppression {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Suppression is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Suppression) String() string {
	var builder strings.Builder
	builder.WriteString("Suppression(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("rule_id=")
	builder.WriteString(_m.RuleID)
	builder.WriteString(", ")
	if v := _m.AssetID; v != nil {
		builder.WriteString("asset_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("matched_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MatchedCount))
	builder.WriteString(", ")
	if v := _m.LastMatchedAt; v != nil {
		builder.WriteString("last_matched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Suppressions is a parsable slice of Suppression.
type Suppressions []*Suppression
