// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"openxdr/server/ent/suppression"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SuppressionCreate is the builder for creating a Suppression entity.
type SuppressionCreate struct {
	config
	mutation *SuppressionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SuppressionCreate) SetCreatedAt(v time.Time) *SuppressionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableCreatedAt(v *time.Time) *SuppressionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRuleID sets the "rule_id" field.
func (_c *SuppressionCreate) SetRuleID(v string) *SuppressionCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetAssetID sets the "asset_id" field.
func (_c *SuppressionCreate) SetAssetID(v uuid.UUID) *SuppressionCreate {
	_c.mutation.SetAssetID(v)
	return _c
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableAssetID(v *uuid.UUID) *SuppressionCreate {
	if v != nil {
		_c.SetAssetID(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *SuppressionCreate) SetReason(v string) *SuppressionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableReason(v *string) *SuppressionCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SuppressionCreate) SetCreatedBy(v string) *SuppressionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableCreatedBy(v *string) *SuppressionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SuppressionCreate) SetExpiresAt(v time.Time) *SuppressionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableExpiresAt(v *time.Time) *SuppressionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetMatchedCount sets the "matched_count" field.
func (_c *SuppressionCreate) SetMatchedCount(v int) *SuppressionCreate {
	_c.mutation.SetMatchedCount(v)
	return _c
}

// SetNillableMatchedCount sets the "matched_count" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableMatchedCount(v *int) *SuppressionCreate {
	if v != nil {
		_c.SetMatchedCount(*v)
	}
	return _c
}

// SetLastMatchedAt sets the "last_matched_at" field.
func (_c *SuppressionCreate) SetLastMatchedAt(v time.Time) *SuppressionCreate {
	_c.mutation.SetLastMatchedAt(v)
	return _c
}

// SetNillableLastMatchedAt sets the "last_matched_at" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableLastMatchedAt(v *time.Time) *SuppressionCreate {
	if v != nil {
		_c.SetLastMatchedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SuppressionCreate) SetID(v uuid.UUID) *SuppressionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SuppressionCreate) SetNillableID(v *uuid.UUID) *SuppressionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SuppressionMutation object of the builder.
func (_c *SuppressionCreate) Mutation() *SuppressionMutation {
	return _c.mutation
}

// Save creates the Suppression in the database.
func (_c *SuppressionCreate) Save(ctx context.Context) (*Suppression, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SuppressionCreate) SaveX(ctx context.Context) *Suppression {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SuppressionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SuppressionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SuppressionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := suppression.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := suppression.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.MatchedCount(); !ok {
		v := suppression.DefaultMatchedCount
		_c.mutation.SetMatchedCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := suppression.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SuppressionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Suppression.created_at"`)}
	}
	if _, ok := _c.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "Suppression.rule_id"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Suppression.created_by"`)}
	}
	if _, ok := _c.mutation.MatchedCount(); !ok {
		return &ValidationError{Name: "matched_count", err: errors.New(`ent: missing required field "Suppression.matched_count"`)}
	}
	return nil
}

func (_c *SuppressionCreate) sqlSave(ctx context.Context) (*Suppression, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SuppressionCreate) createSpec() (*Suppression, *sqlgraph.CreateSpec) {
	var (
		_node = &Suppression{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(suppression.Table, sqlgraph.NewFieldSpec(suppression.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(suppression.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(suppression.FieldRuleID, field.TypeString, value)
		_node.RuleID = value
	}
	if value, ok := _c.mutation.AssetID(); ok {
		_spec.SetField(suppression.FieldAssetID, field.TypeUUID, value)
		_node.AssetID = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(suppression.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(suppression.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(suppression.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.MatchedCount(); ok {
		_spec.SetField(suppression.FieldMatchedCount, field.TypeInt, value)
		_node.MatchedCount = value
	}
	if value, ok := _c.mutation.LastMatchedAt(); ok {
		_spec.SetField(suppression.FieldLastMatchedAt, field.TypeTime, value)
		_node.LastMatchedAt = &value
	}
	return _node, _spec
}

// SuppressionCreateBulk is the builder for creating many Suppression entities in bulk.
type SuppressionCreateBulk struct {
	config
	err      error
	builders []*SuppressionCreate
}

// Save creates the Suppression entities in the database.
func (_c *SuppressionCreateBulk) Save(ctx context.Context) ([]*Suppression, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Suppression, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SuppressionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SuppressionCreateBulk) SaveX(ctx context.Context) []*Suppression {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SuppressionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SuppressionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
