// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Alert is the predicate function for alert builders.
type Alert func(*sql.Selector)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Command is the predicate function for command builders.
type Command func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Incident is the predicate function for incident builders.
type Incident func(*sql.Selector)

// Intel is the predicate function for intel builders.
type Intel func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Suppression is the predicate function for suppression builders.
type Suppression func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
