// Code generated by ent, DO NOT EDIT.

package suppression

import (
	"openxdr/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldCreatedAt, v))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldRuleID, v))
}

// AssetID applies equality check predicate on the "asset_id" field. It's identical to AssetIDEQ.
func AssetID(v uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldAssetID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldReason, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldCreatedBy, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldExpiresAt, v))
}

// MatchedCount applies equality check predicate on the "matched_count" field. It's identical to MatchedCountEQ.
func MatchedCount(v int) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldMatchedCount, v))
}

// LastMatchedAt applies equality check predicate on the "last_matched_at" field. It's identical to LastMatchedAtEQ.
func LastMatchedAt(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldLastMatchedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldCreatedAt, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...string) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...string) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDContains applies the Contains predicate on the "rule_id" field.
func RuleIDContains(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldContains(FieldRuleID, v))
}

// RuleIDHasPrefix applies the HasPrefix predicate on the "rule_id" field.
func RuleIDHasPrefix(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldHasPrefix(FieldRuleID, v))
}

// RuleIDHasSuffix applies the HasSuffix predicate on the "rule_id" field.
func RuleIDHasSuffix(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldHasSuffix(FieldRuleID, v))
}

// RuleIDEqualFold applies the EqualFold predicate on the "rule_id" field.
func RuleIDEqualFold(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEqualFold(FieldRuleID, v))
}

// RuleIDContainsFold applies the ContainsFold predicate on the "rule_id" field.
func RuleIDContainsFold(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldContainsFold(FieldRuleID, v))
}

// AssetIDEQ applies the EQ predicate on the "asset_id" field.
func AssetIDEQ(v uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldAssetID, v))
}

// AssetIDNEQ applies the NEQ predicate on the "asset_id" field.
func AssetIDNEQ(v uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldAssetID, v))
}

// AssetIDIn applies the In predicate on the "asset_id" field.
func AssetIDIn(vs ...uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldAssetID, vs...))
}

// AssetIDNotIn applies the NotIn predicate on the "asset_id" field.
func AssetIDNotIn(vs ...uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldAssetID, vs...))
}

// AssetIDGT applies the GT predicate on the "asset_id" field.
func AssetIDGT(v uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldAssetID, v))
}

// AssetIDGTE applies the GTE predicate on the "asset_id" field.
func AssetIDGTE(v uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldAssetID, v))
}

// AssetIDLT applies the LT predicate on the "asset_id" field.
func AssetIDLT(v uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldAssetID, v))
}

// AssetIDLTE applies the LTE predicate on the "asset_id" field.
func AssetIDLTE(v uuid.UUID) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldAssetID, v))
}

// AssetIDIsNil applies the IsNil predicate on the "asset_id" field.
func AssetIDIsNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldIsNull(FieldAssetID))
}

// AssetIDNotNil applies the NotNil predicate on the "asset_id" field.
func AssetIDNotNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldNotNull(FieldAssetID))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldContainsFold(FieldReason, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Suppression {
	return predicate.Suppression(sql.FieldContainsFold(FieldCreatedBy, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldNotNull(FieldExpiresAt))
}

// MatchedCountEQ applies the EQ predicate on the "matched_count" field.
func MatchedCountEQ(v int) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldMatchedCount, v))
}

// MatchedCountNEQ applies the NEQ predicate on the "matched_count" field.
func MatchedCountNEQ(v int) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldMatchedCount, v))
}

// MatchedCountIn applies the In predicate on the "matched_count" field.
func MatchedCountIn(vs ...int) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldMatchedCount, vs...))
}

// MatchedCountNotIn applies the NotIn predicate on the "matched_count" field.
func MatchedCountNotIn(vs ...int) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldMatchedCount, vs...))
}

// MatchedCountGT applies the GT predicate on the "matched_count" field.
func MatchedCountGT(v int) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldMatchedCount, v))
}

// MatchedCountGTE applies the GTE predicate on the "matched_count" field.
func MatchedCountGTE(v int) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldMatchedCount, v))
}

// MatchedCountLT applies the LT predicate on the "matched_count" field.
func MatchedCountLT(v int) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldMatchedCount, v))
}

// MatchedCountLTE applies the LTE predicate on the "matched_count" field.
func MatchedCountLTE(v int) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldMatchedCount, v))
}

// LastMatchedAtEQ applies the EQ predicate on the "last_matched_at" field.
func LastMatchedAtEQ(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldEQ(FieldLastMatchedAt, v))
}

// LastMatchedAtNEQ applies the NEQ predicate on the "last_matched_at" field.
func LastMatchedAtNEQ(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldNEQ(FieldLastMatchedAt, v))
}

// LastMatchedAtIn applies the In predicate on the "last_matched_at" field.
func LastMatchedAtIn(vs ...time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldIn(FieldLastMatchedAt, vs...))
}

// LastMatchedAtNotIn applies the NotIn predicate on the "last_matched_at" field.
func LastMatchedAtNotIn(vs ...time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldNotIn(FieldLastMatchedAt, vs...))
}

// LastMatchedAtGT applies the GT predicate on the "last_matched_at" field.
func LastMatchedAtGT(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldGT(FieldLastMatchedAt, v))
}

// LastMatchedAtGTE applies the GTE predicate on the "last_matched_at" field.
func LastMatchedAtGTE(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldGTE(FieldLastMatchedAt, v))
}

// LastMatchedAtLT applies the LT predicate on the "last_matched_at" field.
func LastMatchedAtLT(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldLT(FieldLastMatchedAt, v))
}

// LastMatchedAtLTE applies the LTE predicate on the "last_matched_at" field.
func LastMatchedAtLTE(v time.Time) predicate.Suppression {
	return predicate.Suppression(sql.FieldLTE(FieldLastMatchedAt, v))
}

// LastMatchedAtIsNil applies the IsNil predicate on the "last_matched_at" field.
func LastMatchedAtIsNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldIsNull(FieldLastMatchedAt))
}

// LastMatchedAtNotNil applies the NotNil predicate on the "last_matched_at" field.
func LastMatchedAtNotNil() predicate.Suppression {
	return predicate.Suppression(sql.FieldNotNull(FieldLastMatchedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Suppression) predicate.Suppression {
	return predicate.Suppression(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Suppression) predicate.Suppression {
	return predicate.Suppression(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Suppression) predicate.Suppression {
	return predicate.Suppression(sql.NotPredicates(p))
}
