// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlertsColumns holds the columns for the "alerts" table.
	AlertsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "ts", Type: field.TypeTime},
		{Name: "rule_id", Type: field.TypeString},
		{Name: "severity", Type: field.TypeInt16},
		{Name: "count", Type: field.TypeInt, Default: 1},
		{Name: "last_ts", Type: field.TypeTime, Nullable: true},
		{Name: "asset_id", Type: field.TypeUUID, Nullable: true},
		{Name: "event_id", Type: field.TypeUUID, Nullable: true},
		{Name: "incident_id", Type: field.TypeUUID, Nullable: true},
	}
	// AlertsTable holds the schema information for the "alerts" table.
	AlertsTable = &schema.Table{
		Name:       "alerts",
		Columns:    AlertsColumns,
		PrimaryKey: []*schema.Column{AlertsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "alerts_assets_alerts",
				Columns:    []*schema.Column{AlertsColumns[6]},
				RefColumns: []*schema.Column{AssetsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "alerts_events_alerts",
				Columns:    []*schema.Column{AlertsColumns[7]},
				RefColumns: []*schema.Column{EventsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "alerts_incidents_alerts",
				Columns:    []*schema.Column{AlertsColumns[8]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "alert_incident_id",
				Unique:  false,
				Columns: []*schema.Column{AlertsColumns[8]},
			},
			{
				Name:    "alert_asset_id_ts",
				Unique:  false,
				Columns: []*schema.Column{AlertsColumns[6], AlertsColumns[1]},
			},
		},
	}
	// AssetsColumns holds the columns for the "assets" table.
	AssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "hostname", Type: field.TypeString},
		{Name: "os", Type: field.TypeString, Nullable: true},
		{Name: "ip_addrs", Type: field.TypeJSON, Nullable: true},
		{Name: "agent_id", Type: field.TypeUUID, Unique: true, Nullable: true},
		{Name: "first_seen", Type: field.TypeTime},
		{Name: "last_seen", Type: field.TypeTime},
	}
	// AssetsTable holds the schema information for the "assets" table.
	AssetsTable = &schema.Table{
		Name:       "assets",
		Columns:    AssetsColumns,
		PrimaryKey: []*schema.Column{AssetsColumns[0]},
	}
	// CommandsColumns holds the columns for the "commands" table.
	CommandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "kind", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "dry_run", Type: field.TypeBool, Default: true},
		{Name: "incident_id", Type: field.TypeUUID, Nullable: true},
		{Name: "process_guid", Type: field.TypeUUID, Nullable: true},
		{Name: "issued_by", Type: field.TypeString, Default: "api"},
		{Name: "detail", Type: field.TypeString, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "asset_id", Type: field.TypeUUID},
	}
	// CommandsTable holds the schema information for the "commands" table.
	CommandsTable = &schema.Table{
		Name:       "commands",
		Columns:    CommandsColumns,
		PrimaryKey: []*schema.Column{CommandsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "commands_assets_commands",
				Columns:    []*schema.Column{CommandsColumns[10]},
				RefColumns: []*schema.Column{AssetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "command_asset_id_status",
				Unique:  false,
				Columns: []*schema.Column{CommandsColumns[10], CommandsColumns[3]},
			},
			{
				Name:    "command_created_at",
				Unique:  false,
				Columns: []*schema.Column{CommandsColumns[1]},
			},
		},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "ts", Type: field.TypeTime},
		{Name: "class_uid", Type: field.TypeInt},
		{Name: "source", Type: field.TypeString},
		{Name: "process_guid", Type: field.TypeUUID, Nullable: true},
		{Name: "parent_process_guid", Type: field.TypeUUID, Nullable: true},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "conn_tuple", Type: field.TypeString, Nullable: true},
		{Name: "raw", Type: field.TypeJSON},
		{Name: "asset_id", Type: field.TypeUUID, Nullable: true},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_assets_events",
				Columns:    []*schema.Column{EventsColumns[9]},
				RefColumns: []*schema.Column{AssetsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "event_ts",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[1]},
			},
			{
				Name:    "event_asset_id_ts",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[9], EventsColumns[1]},
			},
			{
				Name:    "event_process_guid",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[4]},
			},
			{
				Name:    "event_parent_process_guid",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[5]},
			},
		},
	}
	// IncidentsColumns holds the columns for the "incidents" table.
	IncidentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "open"},
		{Name: "graph", Type: field.TypeJSON},
		{Name: "ai_verdict", Type: field.TypeJSON, Nullable: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
	}
	// IncidentsTable holds the schema information for the "incidents" table.
	IncidentsTable = &schema.Table{
		Name:       "incidents",
		Columns:    IncidentsColumns,
		PrimaryKey: []*schema.Column{IncidentsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlertsTable,
		AssetsTable,
		CommandsTable,
		EventsTable,
		IncidentsTable,
	}
)

func init() {
	AlertsTable.ForeignKeys[0].RefTable = AssetsTable
	AlertsTable.ForeignKeys[1].RefTable = EventsTable
	AlertsTable.ForeignKeys[2].RefTable = IncidentsTable
	CommandsTable.ForeignKeys[0].RefTable = AssetsTable
	EventsTable.ForeignKeys[0].RefTable = AssetsTable
}
