// Code generated by ent, DO NOT EDIT.

package command

import (
	"openxdr/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldCreatedAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldKind, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldStatus, v))
}

// DryRun applies equality check predicate on the "dry_run" field. It's identical to DryRunEQ.
func DryRun(v bool) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldDryRun, v))
}

// AssetID applies equality check predicate on the "asset_id" field. It's identical to AssetIDEQ.
func AssetID(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldAssetID, v))
}

// IncidentID applies equality check predicate on the "incident_id" field. It's identical to IncidentIDEQ.
func IncidentID(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldIncidentID, v))
}

// ProcessGUID applies equality check predicate on the "process_guid" field. It's identical to ProcessGUIDEQ.
func ProcessGUID(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldProcessGUID, v))
}

// IssuedBy applies equality check predicate on the "issued_by" field. It's identical to IssuedByEQ.
func IssuedBy(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldIssuedBy, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldDetail, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldCreatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Command {
	return predicate.Command(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Command {
	return predicate.Command(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Command {
	return predicate.Command(sql.FieldContainsFold(FieldKind, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Command {
	return predicate.Command(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Command {
	return predicate.Command(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Command {
	return predicate.Command(sql.FieldContainsFold(FieldStatus, v))
}

// DryRunEQ applies the EQ predicate on the "dry_run" field.
func DryRunEQ(v bool) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldDryRun, v))
}

// DryRunNEQ applies the NEQ predicate on the "dry_run" field.
func DryRunNEQ(v bool) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldDryRun, v))
}

// AssetIDEQ applies the EQ predicate on the "asset_id" field.
func AssetIDEQ(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldAssetID, v))
}

// AssetIDNEQ applies the NEQ predicate on the "asset_id" field.
func AssetIDNEQ(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldAssetID, v))
}

// AssetIDIn applies the In predicate on the "asset_id" field.
func AssetIDIn(vs ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldAssetID, vs...))
}

// AssetIDNotIn applies the NotIn predicate on the "asset_id" field.
func AssetIDNotIn(vs ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldAssetID, vs...))
}

// IncidentIDEQ applies the EQ predicate on the "incident_id" field.
func IncidentIDEQ(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldIncidentID, v))
}

// IncidentIDNEQ applies the NEQ predicate on the "incident_id" field.
func IncidentIDNEQ(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldIncidentID, v))
}

// IncidentIDIn applies the In predicate on the "incident_id" field.
func IncidentIDIn(vs ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldIncidentID, vs...))
}

// IncidentIDNotIn applies the NotIn predicate on the "incident_id" field.
func IncidentIDNotIn(vs ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldIncidentID, vs...))
}

// IncidentIDGT applies the GT predicate on the "incident_id" field.
func IncidentIDGT(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldIncidentID, v))
}

// IncidentIDGTE applies the GTE predicate on the "incident_id" field.
func IncidentIDGTE(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldIncidentID, v))
}

// IncidentIDLT applies the LT predicate on the "incident_id" field.
func IncidentIDLT(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldIncidentID, v))
}

// IncidentIDLTE applies the LTE predicate on the "incident_id" field.
func IncidentIDLTE(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldIncidentID, v))
}

// IncidentIDIsNil applies the IsNil predicate on the "incident_id" field.
func IncidentIDIsNil() predicate.Command {
	return predicate.Command(sql.FieldIsNull(FieldIncidentID))
}

// IncidentIDNotNil applies the NotNil predicate on the "incident_id" field.
func IncidentIDNotNil() predicate.Command {
	return predicate.Command(sql.FieldNotNull(FieldIncidentID))
}

// ProcessGUIDEQ applies the EQ predicate on the "process_guid" field.
func ProcessGUIDEQ(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldProcessGUID, v))
}

// ProcessGUIDNEQ applies the NEQ predicate on the "process_guid" field.
func ProcessGUIDNEQ(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldProcessGUID, v))
}

// ProcessGUIDIn applies the In predicate on the "process_guid" field.
func ProcessGUIDIn(vs ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldProcessGUID, vs...))
}

// ProcessGUIDNotIn applies the NotIn predicate on the "process_guid" field.
func ProcessGUIDNotIn(vs ...uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldProcessGUID, vs...))
}

// ProcessGUIDGT applies the GT predicate on the "process_guid" field.
func ProcessGUIDGT(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldProcessGUID, v))
}

// ProcessGUIDGTE applies the GTE predicate on the "process_guid" field.
func ProcessGUIDGTE(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldProcessGUID, v))
}

// ProcessGUIDLT applies the LT predicate on the "process_guid" field.
func ProcessGUIDLT(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldProcessGUID, v))
}

// ProcessGUIDLTE applies the LTE predicate on the "process_guid" field.
func ProcessGUIDLTE(v uuid.UUID) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldProcessGUID, v))
}

// ProcessGUIDIsNil applies the IsNil predicate on the "process_guid" field.
func ProcessGUIDIsNil() predicate.Command {
	return predicate.Command(sql.FieldIsNull(FieldProcessGUID))
}

// ProcessGUIDNotNil applies the NotNil predicate on the "process_guid" field.
func ProcessGUIDNotNil() predicate.Command {
	return predicate.Command(sql.FieldNotNull(FieldProcessGUID))
}

// IssuedByEQ applies the EQ predicate on the "issued_by" field.
func IssuedByEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByNEQ applies the NEQ predicate on the "issued_by" field.
func IssuedByNEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldIssuedBy, v))
}

// IssuedByIn applies the In predicate on the "issued_by" field.
func IssuedByIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldIssuedBy, vs...))
}

// IssuedByNotIn applies the NotIn predicate on the "issued_by" field.
func IssuedByNotIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldIssuedBy, vs...))
}

// IssuedByGT applies the GT predicate on the "issued_by" field.
func IssuedByGT(v string) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldIssuedBy, v))
}

// IssuedByGTE applies the GTE predicate on the "issued_by" field.
func IssuedByGTE(v string) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldIssuedBy, v))
}

// IssuedByLT applies the LT predicate on the "issued_by" field.
func IssuedByLT(v string) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldIssuedBy, v))
}

// IssuedByLTE applies the LTE predicate on the "issued_by" field.
func IssuedByLTE(v string) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldIssuedBy, v))
}

// IssuedByContains applies the Contains predicate on the "issued_by" field.
func IssuedByContains(v string) predicate.Command {
	return predicate.Command(sql.FieldContains(FieldIssuedBy, v))
}

// IssuedByHasPrefix applies the HasPrefix predicate on the "issued_by" field.
func IssuedByHasPrefix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasPrefix(FieldIssuedBy, v))
}

// IssuedByHasSuffix applies the HasSuffix predicate on the "issued_by" field.
func IssuedByHasSuffix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasSuffix(FieldIssuedBy, v))
}

// IssuedByEqualFold applies the EqualFold predicate on the "issued_by" field.
func IssuedByEqualFold(v string) predicate.Command {
	return predicate.Command(sql.FieldEqualFold(FieldIssuedBy, v))
}

// IssuedByContainsFold applies the ContainsFold predicate on the "issued_by" field.
func IssuedByContainsFold(v string) predicate.Command {
	return predicate.Command(sql.FieldContainsFold(FieldIssuedBy, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.Command {
	return predicate.Command(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.Command {
	return predicate.Command(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.Command {
	return predicate.Command(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.Command {
	return predicate.Command(sql.FieldNotNull(FieldDetail))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.Command {
	return predicate.Command(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.Command {
	return predicate.Command(sql.FieldContainsFold(FieldDetail, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Command {
	return predicate.Command(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Command {
	return predicate.Command(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Command {
	return predicate.Command(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Command {
	return predicate.Command(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Command {
	return predicate.Command(sql.FieldNotNull(FieldCompletedAt))
}

// HasAsset applies the HasEdge predicate on the "asset" edge.
func HasAsset() predicate.Command {
	return predicate.Command(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.Asset) predicate.Command {
	return predicate.Command(func(s *sql.Selector) {
		step := newAssetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Command) predicate.Command {
	return predicate.Command(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Command) predicate.Command {
	return predicate.Command(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Command) predicate.Command {
	return predicate.Command(sql.NotPredicates(p))
}
