// Code generated by ent, DO NOT EDIT.

package intel

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the intel type in the database.
	Label = "intel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldMatchedCount holds the string denoting the matched_count field in the database.
	FieldMatchedCount = "matched_count"
	// FieldLastMatchedAt holds the string denoting the last_matched_at field in the database.
	FieldLastMatchedAt = "last_matched_at"
	// Table holds the table name of the intel in the database.
	Table = "intels"
)

// Columns holds all SQL columns for intel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldKind,
	FieldValue,
	FieldSource,
	FieldSeverity,
	FieldNote,
	FieldExpiresAt,
	FieldMatchedCount,
	FieldLastMatchedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultSeverity holds the default value on creation for the "severity" field.
	DefaultSeverity int16
	// DefaultMatchedCount holds the default value on creation for the "matched_count" field.
	DefaultMatchedCount int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindIP     Kind = "ip"
	KindDomain Kind = "domain"
	KindHash   Kind = "hash"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindIP, KindDomain, KindHash:
		return nil
	default:
		return fmt.Errorf("intel: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the Intel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByMatchedCount orders the results by the matched_count field.
func ByMatchedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedCount, opts...).ToFunc()
}

// ByLastMatchedAt orders the results by the last_matched_at field.
func ByLastMatchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMatchedAt, opts...).ToFunc()
}
