// <auto-generated />
using System;
using System.Net;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenXDR.Server.Data;

#nullable disable

namespace OpenXDR.Server.Migrations
{
    [DbContext(typeof(OpenXdrDbContext))]
    [Migration("20260807121555_AlertDedup")]
    partial class AlertDedup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenXDR.Server.Data.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTimeOffset?>("LastTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ts");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_alerts_asset_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_alerts_event_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_alerts_incident_id");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("OpenXDR.Server.Data.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.PrimitiveCollection<IPAddress[]>("IpAddrs")
                        .HasColumnType("inet[]")
                        .HasColumnName("ip_addrs");

                    b.Property<DateTimeOffset>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Os")
                        .HasColumnType("text")
                        .HasColumnName("os");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AgentId")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_agent_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("OpenXDR.Server.Data.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int>("ClassUid")
                        .HasColumnType("integer")
                        .HasColumnName("class_uid");

                    b.Property<string>("ConnTuple")
                        .HasColumnType("text")
                        .HasColumnName("conn_tuple");

                    b.Property<Guid?>("ProcessGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("process_guid");

                    b.Property<JsonDocument>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("ProcessGuid")
                        .HasDatabaseName("ix_events_process_guid")
                        .HasFilter("process_guid IS NOT NULL");

                    b.HasIndex("Ts")
                        .HasDatabaseName("ix_events_ts");

                    b.HasIndex("AssetId", "Ts")
                        .HasDatabaseName("ix_events_asset_id_ts");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("OpenXDR.Server.Data.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("AiVerdict")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_verdict");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Graph")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("graph");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("OpenXDR.Server.Data.Alert", b =>
                {
                    b.HasOne("OpenXDR.Server.Data.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_alerts_assets_asset_id");

                    b.HasOne("OpenXDR.Server.Data.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("fk_alerts_events_event_id");

                    b.Navigation("Asset");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("OpenXDR.Server.Data.Event", b =>
                {
                    b.HasOne("OpenXDR.Server.Data.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_events_assets_asset_id");

                    b.Navigation("Asset");
                });
#pragma warning restore 612, 618
        }
    }
}
